// Copyleft 2005 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
        chris korda
 
		revision history:
		rev		date	comments
		00		30aug05	initial version

        AVI file error codes
 
*/

AVIFILEERR(AVIERR_UNSUPPORTED)
AVIFILEERR(AVIERR_BADFORMAT)
AVIFILEERR(AVIERR_MEMORY)
AVIFILEERR(AVIERR_INTERNAL)
AVIFILEERR(AVIERR_BADFLAGS)
AVIFILEERR(AVIERR_BADPARAM)
AVIFILEERR(AVIERR_BADSIZE)
AVIFILEERR(AVIERR_BADHANDLE)
AVIFILEERR(AVIERR_FILEREAD)
AVIFILEERR(AVIERR_FILEWRITE)
AVIFILEERR(AVIERR_FILEOPEN)
AVIFILEERR(AVIERR_COMPRESSOR)
AVIFILEERR(AVIERR_NOCOMPRESSOR)
AVIFILEERR(AVIERR_READONLY)
AVIFILEERR(AVIERR_NODATA)
AVIFILEERR(AVIERR_BUFFERTOOSMALL)
AVIFILEERR(AVIERR_CANTCOMPRESS)
AVIFILEERR(AVIERR_USERABORT)
AVIFILEERR(AVIERR_ERROR)
