// Copyleft 2005 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
		chris korda

		rev		date	comments
		00		19jul05	initial version

		DirectInput error codes

*/

DIRINPUTERR(DIERR_OLDDIRECTINPUTVERSION)
DIRINPUTERR(DIERR_BETADIRECTINPUTVERSION)
DIRINPUTERR(DIERR_BADDRIVERVER)
DIRINPUTERR(DIERR_DEVICENOTREG)
DIRINPUTERR(DIERR_NOTFOUND)
DIRINPUTERR(DIERR_OBJECTNOTFOUND)
DIRINPUTERR(DIERR_INVALIDPARAM)
DIRINPUTERR(DIERR_NOINTERFACE)
DIRINPUTERR(DIERR_GENERIC)
DIRINPUTERR(DIERR_OUTOFMEMORY)
DIRINPUTERR(DIERR_UNSUPPORTED)
DIRINPUTERR(DIERR_NOTINITIALIZED)
DIRINPUTERR(DIERR_ALREADYINITIALIZED)
DIRINPUTERR(DIERR_NOAGGREGATION)
DIRINPUTERR(DIERR_OTHERAPPHASPRIO)
DIRINPUTERR(DIERR_INPUTLOST)
DIRINPUTERR(DIERR_ACQUIRED)
DIRINPUTERR(DIERR_NOTACQUIRED)
DIRINPUTERR(DIERR_READONLY)
DIRINPUTERR(DIERR_HANDLEEXISTS)
DIRINPUTERR(DIERR_INSUFFICIENTPRIVS)
DIRINPUTERR(DIERR_DEVICEFULL)
DIRINPUTERR(DIERR_MOREDATA)
DIRINPUTERR(DIERR_NOTDOWNLOADED)
DIRINPUTERR(DIERR_HASEFFECTS)
DIRINPUTERR(DIERR_NOTEXCLUSIVEACQUIRED)
DIRINPUTERR(DIERR_INCOMPLETEEFFECT)
DIRINPUTERR(DIERR_NOTBUFFERED)
DIRINPUTERR(DIERR_EFFECTPLAYING)
DIRINPUTERR(DIERR_UNPLUGGED)
DIRINPUTERR(DIERR_REPORTFULL)
