//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Whorld.rc
//
#define IDR_MAINFRAME                   101
#define IDR_MAIN_FOCUS                  102
#define IDR_PLAYLIST                    103
#define IDR_PLAYLIST_CONTEXT            104
#define IDR_SNAPSHOT                    105
#define IDR_WHORLDTYPE                  106
#define IDR_WHORLD_MOVIE                107
#define IDR_WHORLD_PLAYLIST             108
#define IDR_WHORLD_SNAPSHOT             109
#define IDI_GOTO_END                    110
#define IDI_GOTO_START                  111
#define IDI_LOOPD                       112
#define IDI_LOOPU                       113
#define IDI_OPEN                        114
#define IDI_PAUSED                      115
#define IDI_PAUSEU                      116
#define IDI_PLAYD                       117
#define IDI_PLAYU                       118
#define IDI_PL_NORMAL                   119
#define IDI_PL_PLAYING                  120
#define IDI_PL_XFADING                  121
#define IDI_SAVE                        122
#define IDI_SET_IN                      123
#define IDI_SET_OUT                     124
#define IDI_STOPD                       125
#define IDI_STOPU                       126
#define IDI_TAKE_SNAP                   127
#define IDD_ABOUTBOX                    128
#define IDD_CROSS                       129
#define IDD_EXPORT                      130
#define IDD_FILE_SEARCH_DLG             131
#define IDD_MASTER                      132
#define IDD_MIDI_AUTO_ASSIGN            133
#define IDD_MIDI_SETUP                  134
#define IDD_MIDI_SETUP_ROW              135
#define IDD_MISSING_FILES_DLG           136
#define IDD_MOVIE_EXPORT                137
#define IDD_MOVIE_PLAYER                138
#define IDD_MOVIE_RESIZE                139
#define IDD_MULTI_FILE                  140
#define IDD_NUMBERS                     141
#define IDD_OPTS_DISPLAY                142
#define IDD_OPTS_FOLDER                 143
#define IDD_OPTS_INPUT                  144
#define IDD_OPTS_MIDI                   145
#define IDD_PARMS                       146
#define IDD_PARM_ROW                    147
#define IDD_PLAYLIST                    148
#define IDD_PLAYLIST_MIDI               149
#define IDD_POPUP_MSG                   150
#define IDD_PROGRESS                    151
#define IDD_REPLACE_FILES_DLG           152
#define IDD_ROW_DIALOG_FORM             153
#define IDD_SLIDE_SHOW                  154
#define IDD_VIDEO_COMPR                 155
#define IDS_APP_ABOUT_TEXT              200
#define IDS_APP_CREDITS                 201
#define IDS_APP_LICENSE                 202
#define IDS_BTAE_ADD_COMPR              203
#define IDS_BTAE_ADD_FRAME              204
#define IDS_BTAE_ADD_MUX                205
#define IDS_BTAE_ADD_SOURCE             206
#define IDS_BTAE_ADD_WRITER             207
#define IDS_BTAE_CONNECT_COMPR          208
#define IDS_BTAE_CONNECT_MUX            209
#define IDS_BTAE_CONNECT_WRITER         210
#define IDS_BTAE_CREATE_GRAPH           211
#define IDS_BTAE_CREATE_MUX             212
#define IDS_BTAE_CREATE_SOURCE          213
#define IDS_BTAE_CREATE_WRITER          214
#define IDS_BTAE_GET_BMPTOAVI           215
#define IDS_BTAE_GET_CONTROL            216
#define IDS_BTAE_GET_EVENT              217
#define IDS_BTAE_GET_FILE_SINK          218
#define IDS_BTAE_GET_PIN                219
#define IDS_BTAE_INIT_COM               220
#define IDS_BTAE_RUN_GRAPH              221
#define IDS_BTAE_SET_FILE_NAME          222
#define IDS_BTAE_SET_PARMS              223
#define IDS_BTAE_STOP_GRAPH             224
#define IDS_BTAE_SUCCESS                225
#define IDS_CANT_CREATE_SURFACE         226
#define IDS_CANT_DETACH                 227
#define IDS_CANT_EXPORT_AVI             228
#define IDS_CANT_HOOK_KEYBD             229
#define IDS_CANT_LAUNCH_TIMER           230
#define IDS_CF_MIX_NAME                 231
#define IDS_CF_SAVE_PROMPT              232
#define IDS_CREATING_THUMBS             233
#define IDS_DD_CANT_CREATE              234
#define IDS_DD_CANT_CREATE_SURFACE      235
#define IDS_DD_TRY_GDI                  236
#define IDS_DI_CANT_CREATE              237
#define IDS_DOC_BAD_FORMAT              238
#define IDS_FILTER_AVI                  239
#define IDS_FILTER_BMP                  240
#define IDS_FILTER_MAIN                 241
#define IDS_FILTER_MOVIE                242
#define IDS_FILTER_PATCH                243
#define IDS_FILTER_PATCH_LINK           244
#define IDS_FILTER_PLAYLIST             245
#define IDS_FILTER_SNAPSHOT             246
#define IDS_FILTER_THUMBS               247
#define IDS_GDI_CANT_CREATE             248
#define IDS_HLINK_CANT_LAUNCH           249
#define IDS_MAA_CTRL                    250
#define IDS_MAA_NOTE                    251
#define IDS_MAST_MAX_RINGS              252
#define IDS_MEX_BAD_FRAME_RANGE         253
#define IDS_MEX_CUSTOM                  254
#define IDS_MEX_NOT_ENOUGH_DISK         255
#define IDS_MF_CANT_EXPORT              256
#define IDS_MF_CANT_RANDOM_PATCH        257
#define IDS_MF_DEMO_BROWSE              258
#define IDS_MF_EXPORT                   259
#define IDS_MF_HELP_FILE_MISSING        260
#define IDS_MF_RECORD                   261
#define IDS_MF_SAVE_MIX                 262
#define IDS_MF_STOP                     263
#define IDS_MF_VEEJAY_MODE_TEXT         264
#define IDS_MF_VEEJAY_MODE_TITLE        265
#define IDS_MF_VIEW_DEMO_TEXT           266
#define IDS_MF_VIEW_DEMO_TITLE          267
#define IDS_MIDI_CANT_CREATE            268
#define IDS_MOVIE_OPEN                  269
#define IDS_MOVIE_RECORD                270
#define IDS_MP_AUTOPLAY                 271
#define IDS_MP_BANK                     272
#define IDS_MP_CANVAS_SCALE             273
#define IDS_MP_CLEAR                    274
#define IDS_MP_CONVEX                   275
#define IDS_MP_COPIES                   276
#define IDS_MP_DAMPING                  277
#define IDS_MP_FILL                     278
#define IDS_MP_HUE                      279
#define IDS_MP_HUE_LOOP_LENGTH          280
#define IDS_MP_INVERT_COLOR             281
#define IDS_MP_LOAD_NEXT_A              282
#define IDS_MP_LOAD_NEXT_B              283
#define IDS_MP_LOOP_HUE                 284
#define IDS_MP_MIRROR                   285
#define IDS_MP_ORIGIN_X                 286
#define IDS_MP_ORIGIN_Y                 287
#define IDS_MP_OUTLINE                  288
#define IDS_MP_PATCH_MODE               289
#define IDS_MP_PATCH_SECS               290
#define IDS_MP_PAUSE                    291
#define IDS_MP_RANDOM_PATCH             292
#define IDS_MP_RANDOM_PHASE             293
#define IDS_MP_REVERSE                  294
#define IDS_MP_RINGS                    295
#define IDS_MP_ROTATE_HUE               296
#define IDS_MP_SPEED                    297
#define IDS_MP_SPREAD                   298
#define IDS_MP_TOGGLE_ORIGIN            299
#define IDS_MP_TRAIL                    300
#define IDS_MP_VIDEO_BLENDING           301
#define IDS_MP_VIDEO_CYCLE              302
#define IDS_MP_VIDEO_CYCLE_LEN          303
#define IDS_MP_VIDEO_ORIGIN_X           304
#define IDS_MP_VIDEO_ORIGIN_Y           305
#define IDS_MP_VIDEO_RAND_ORG           306
#define IDS_MP_VIDEO_SELECT             307
#define IDS_MP_XFADE_LOOP               308
#define IDS_MP_XFADE_PLAY               309
#define IDS_MP_XFADE_POS                310
#define IDS_MP_XFADE_SECS               311
#define IDS_MP_XRAY                     312
#define IDS_MP_ZOOM                     313
#define IDS_MP_ZOOM_CENTER              314
#define IDS_MS_CHAN                     315
#define IDS_MS_CTRL                     316
#define IDS_MS_EVENT                    317
#define IDS_MS_GLOB_PREFIX              318
#define IDS_MS_NONE                     319
#define IDS_MS_OSC_AMP                  320
#define IDS_MS_OSC_FREQ                 321
#define IDS_MS_OSC_PW                   322
#define IDS_MS_OSC_WAVE                 323
#define IDS_MS_RANGE                    324
#define IDS_MS_RESTORE_DEFAULT          325
#define IDS_MS_VALUE                    326
#define IDS_OPTIONS                     327
#define IDS_OP_MUST_RESTART             328
#define IDS_OP_NO_MIDI_IN               329
#define IDS_OP_RESET_ALL                330
#define IDS_OP_VIDEO_MEM                331
#define IDS_ORG_MOTION_DRAG             332
#define IDS_ORG_MOTION_RANDOM           333
#define IDS_PL_AUTO_ASSIGN_KEYS         334
#define IDS_PL_AUTO_ASSIGN_WARN         335
#define IDS_PL_BAD_PATCH                336
#define IDS_PL_BAD_VIDEO                337
#define IDS_PL_CACHING_VIDEOS           338
#define IDS_PL_CANT_READ                339
#define IDS_PL_CANT_WRITE               340
#define IDS_PL_COL_KEY                  341
#define IDS_PL_COL_NAME                 342
#define IDS_PL_COL_PATH                 343
#define IDS_PL_IMPORT_MIDI_SETUP        344
#define IDS_PL_INSERT_PATCHES           345
#define IDS_PL_KEY_ASSIGNED             346
#define IDS_PL_KEY_RESERVED             347
#define IDS_PL_NO_PATCHES               348
#define IDS_PL_OPEN                     349
#define IDS_PL_SAVE_AS                  350
#define IDS_PL_SAVE_PROMPT              351
#define IDS_PL_UNTITLED                 352
#define IDS_PM_AMP                      353
#define IDS_PM_FREQ                     354
#define IDS_PM_PW                       355
#define IDS_PM_SLIDER                   356
#define IDS_PM_VALUE                    357
#define IDS_PM_WAVE                     358
#define IDS_RPLF_FILENAME               359
#define IDS_RPLF_MISSING                360
#define IDS_RPLF_REPLACED               361
#define IDS_RPLF_STATUS                 362
#define IDS_SNAP_LOAD                   363
#define IDS_SNAP_TAKE                   364
#define IDS_SS_SLIDE_NUMBER             365
#define IDS_VCDE_CONNECT                366
#define IDS_VCDE_GET_GRAPH              367
#define IDS_VCDE_GET_STATE              368
#define IDS_VCDE_INIT_COM               369
#define IDS_VCDE_SET_DATA_RATE          370
#define IDS_VCDE_SET_KEY_FRAMES         371
#define IDS_VCDE_SET_PFRAMES            372
#define IDS_VCDE_SET_QUALITY            373
#define IDS_VCDE_SET_STATE              374
#define IDS_VCDE_SET_WND_SIZE           375
#define IDS_VCDE_SHOW_ABOUT             376
#define IDS_VCDE_SHOW_CONFIG            377
#define IDS_VCD_UNCOMPRESSED            378
#define IDS_VL_CANT_LOAD_MOVIE          379
#define IDS_VP_ASPECT_RATIO             380
#define IDS_VP_BK_HUE                   381
#define IDS_VP_BK_LIGHTNESS             382
#define IDS_VP_BK_SATURATION            383
#define IDS_VP_COLOR_SPEED              384
#define IDS_VP_EVEN_CURVE               385
#define IDS_VP_EVEN_SHEAR               386
#define IDS_VP_HUE                      387
#define IDS_VP_LIGHTNESS                388
#define IDS_VP_LINE_WIDTH               389
#define IDS_VP_ODD_CURVE                390
#define IDS_VP_ODD_SHEAR                391
#define IDS_VP_ORIGIN_X                 392
#define IDS_VP_ORIGIN_Y                 393
#define IDS_VP_PINWHEEL                 394
#define IDS_VP_POLY_SIDES               395
#define IDS_VP_RING_COUNT               396
#define IDS_VP_RING_GROWTH              397
#define IDS_VP_RING_SPACING             398
#define IDS_VP_ROTATE_SPEED             399
#define IDS_VP_ROTATION                 400
#define IDS_VP_SATURATION               401
#define IDS_VP_SKEW_ANGLE               402
#define IDS_VP_SKEW_RADIUS              403
#define IDS_VP_STAR_FACTOR              404
#define IDS_WAVE_PULSE                  405
#define IDS_WAVE_RAMP_DOWN              406
#define IDS_WAVE_RAMP_UP                407
#define IDS_WAVE_RANDOM                 408
#define IDS_WAVE_RANDOM_RAMP            409
#define IDS_WAVE_SINE                   410
#define IDS_WAVE_SQUARE                 411
#define IDS_WAVE_TRIANGLE               412
#define IDC_ABOUT_CREDITS               1001
#define IDC_ABOUT_LICENSE               1002
#define IDC_ABOUT_TEXT                  1003
#define IDC_ABOUT_URL                   1004
#define IDC_DRAG_MULTI                  1005
#define IDC_DRAG_SINGLE                 1006
#define IDC_EXP_HEIGHT                  1007
#define IDC_EXP_RESOLUTION              1008
#define IDC_EXP_SCALE_TO_FIT            1009
#define IDC_EXP_SCALE_TO_FIT2           1010
#define IDC_EXP_USE_WND_SIZE            1011
#define IDC_EXP_WIDTH                   1012
#define IDC_MAA_CHAN                    1013
#define IDC_MAA_CHAN_RANGE              1014
#define IDC_MAA_CHAN_SPIN               1015
#define IDC_MAA_EVENT                   1016
#define IDC_MAA_EVENT2                  1017
#define IDC_MAA_EVENT3                  1018
#define IDC_MAA_PARAM                   1019
#define IDC_MAA_PARAM_RANGE             1020
#define IDC_MAA_PARAM_SPIN              1021
#define IDC_MAA_PARM_CAP                1022
#define IDC_MAA_PROP_FIRST              1023
#define IDC_MAA_PROP_LAST               1024
#define IDC_MAA_PROP_RANGE              1025
#define IDC_MAA_PROP_RANGE2             1026
#define IDC_MAA_SET_CHAN_ONLY           1027
#define IDC_MAST_CANVAS_EDIT            1028
#define IDC_MAST_CANVAS_SLIDER          1029
#define IDC_MAST_COPIES_EDIT            1030
#define IDC_MAST_COPIES_SLIDER          1031
#define IDC_MAST_DAMPING_EDIT           1032
#define IDC_MAST_DAMPING_SLIDER         1033
#define IDC_MAST_HUE_LOOP_EDIT          1034
#define IDC_MAST_HUE_LOOP_SLIDER        1035
#define IDC_MAST_RINGS_EDIT             1036
#define IDC_MAST_RINGS_SLIDER           1037
#define IDC_MAST_SPEED_EDIT             1038
#define IDC_MAST_SPEED_SLIDER           1039
#define IDC_MAST_SPREAD_EDIT            1040
#define IDC_MAST_SPREAD_SLIDER          1041
#define IDC_MAST_TEMPO_EDIT             1042
#define IDC_MAST_TEMPO_SLIDER           1043
#define IDC_MAST_TRAIL_EDIT             1044
#define IDC_MAST_TRAIL_SLIDER           1045
#define IDC_MAST_ZOOM_EDIT              1046
#define IDC_MAST_ZOOM_SLIDER            1047
#define IDC_MEX_DISPLAY_OUTPUT          1048
#define IDC_MEX_EXPORT_BITMAPS          1049
#define IDC_MEX_IN_FRAME_RATE           1050
#define IDC_MEX_IN_LENGTH               1051
#define IDC_MEX_IN_SIZE                 1052
#define IDC_MEX_OUT_FRAME_RATE          1053
#define IDC_MEX_OUT_HEIGHT              1054
#define IDC_MEX_OUT_LENGTH              1055
#define IDC_MEX_OUT_SIZE                1056
#define IDC_MEX_OUT_WIDTH               1057
#define IDC_MEX_RANGE_FIRST             1058
#define IDC_MEX_RANGE_LAST              1059
#define IDC_MEX_RANGE_SUBSET            1060
#define IDC_MEX_RANGE_SUBSET2           1061
#define IDC_MEX_SCALE_TO_FIT            1062
#define IDC_MISF_OPENDLG                1063
#define IDC_MISF_PROCEED                1064
#define IDC_MP_GOTO_END                 1065
#define IDC_MP_GOTO_START               1066
#define IDC_MP_LOOP                     1067
#define IDC_MP_OPEN                     1068
#define IDC_MP_PAUSE                    1069
#define IDC_MP_PLAY                     1070
#define IDC_MP_POS                      1071
#define IDC_MP_SAVE                     1072
#define IDC_MP_SET_IN                   1073
#define IDC_MP_SET_OUT                  1074
#define IDC_MP_STOP                     1075
#define IDC_MP_TAKE_SNAP                1076
#define IDC_MP_TIME                     1077
#define IDC_MRS_HEIGHT                  1078
#define IDC_MRS_WIDTH                   1079
#define IDC_MS_ADVANCED                 1080
#define IDC_MS_AUTO_ASSIGN              1081
#define IDC_MS_CHAN                     1082
#define IDC_MS_CHAN_SPIN                1083
#define IDC_MS_CTRL                     1084
#define IDC_MS_CTRL_SPIN                1085
#define IDC_MS_EVENT                    1086
#define IDC_MS_LEARN                    1087
#define IDC_MS_RANGE_END                1088
#define IDC_MS_RANGE_END_SPIN           1089
#define IDC_MS_RANGE_START              1090
#define IDC_MS_RANGE_START_SPIN         1091
#define IDC_MS_RESTORE_DEFAULTS         1092
#define IDC_MS_TITLE                    1093
#define IDC_MS_VALUE                    1094
#define IDC_MS_ZERO_CONTROLS            1095
#define IDC_MULTI_FILE_PREVIEW          1096
#define IDC_OP_ALLOW_EXCLUSIVE          1097
#define IDC_OP_BACK_BUF_LOC             1098
#define IDC_OP_FRAME_RATE               1099
#define IDC_OP_FRAME_RATE_SPIN          1100
#define IDC_OP_MIDI_DEV                 1101
#define IDC_OP_MIDI_SYNC                1102
#define IDC_OP_MIRROR_PRECISE           1103
#define IDC_OP_MOUSE_SENS_EDIT          1104
#define IDC_OP_MOUSE_SENS_SLIDER        1105
#define IDC_OP_PRINT_FROM_BITMAP        1106
#define IDC_OP_RESET_ALL                1107
#define IDC_OP_SNAP_FOLDER_ALWAYS       1108
#define IDC_OP_SNAP_FOLDER_ALWAYS2      1109
#define IDC_OP_SNAP_FOLDER_BROWSE       1110
#define IDC_OP_SNAP_FOLDER_EDIT         1111
#define IDC_OP_TEMPO_NUDGE_EDIT         1112
#define IDC_OP_TEMPO_NUDGE_SLIDER       1113
#define IDC_OP_USE_DIRDRAW              1114
#define IDC_OP_WHEEL_SENS_EDIT          1115
#define IDC_OP_WHEEL_SENS_SLIDER        1116
#define IDC_PLM_CHAN                    1117
#define IDC_PLM_CHAN_SPIN               1118
#define IDC_PLM_FIRST                   1119
#define IDC_PLM_FIRST_SPIN              1120
#define IDC_PLM_LAST                    1121
#define IDC_PLM_LAST_SPIN               1122
#define IDC_PLM_SCHEME                  1123
#define IDC_PLM_SCHEME2                 1124
#define IDC_PLM_SCHEME3                 1125
#define IDC_PL_AUTOPLAY_CAP             1126
#define IDC_PL_BANK                     1127
#define IDC_PL_BANK_CAP                 1128
#define IDC_PL_HOTKEY                   1129
#define IDC_PL_HOTKEY_CAP               1130
#define IDC_PL_LIST                     1131
#define IDC_PL_PATCH_SECS_CAP           1132
#define IDC_PL_PATCH_SECS_EDIT          1133
#define IDC_PL_PATCH_SECS_SPIN          1134
#define IDC_PL_PLAY                     1135
#define IDC_PL_SHUFFLE                  1136
#define IDC_PL_XFADE_SECS_CAP           1137
#define IDC_PL_XFADE_SECS_EDIT          1138
#define IDC_PL_XFADE_SECS_SPIN          1139
#define IDC_PL_XFADE_SLIDER             1140
#define IDC_PM_MOD_AMP                  1141
#define IDC_PM_MOD_AMP_SPIN             1142
#define IDC_PM_MOD_FREQ                 1143
#define IDC_PM_MOD_FREQ_SPIN            1144
#define IDC_PM_MOD_PW                   1145
#define IDC_PM_MOD_PW_SPIN              1146
#define IDC_PM_MOD_WAVE                 1147
#define IDC_PM_PARM_EDIT                1148
#define IDC_PM_PARM_SLIDER              1149
#define IDC_PM_PARM_SPIN                1150
#define IDC_PM_TITLE                    1151
#define IDC_PROGRESS                    1152
#define IDC_RES_CAPS                    1153
#define IDC_RES_VALS                    1154
#define IDC_RPLF_BROWSE                 1155
#define IDC_RPLF_LIST                   1156
#define IDC_RPLF_SEARCH_ALL             1157
#define IDC_RPLF_SEARCH_FOLDER          1158
#define IDC_SCALE_TO_FIT2               1159
#define IDC_SS_FULL_SCREEN              1160
#define IDC_SS_LOOP                     1161
#define IDC_SS_SECONDS                  1162
#define IDC_SS_SECS_SPIN                1163
#define IDC_STATUS                      1164
#define IDC_VCD_ABOUT                   1165
#define IDC_VCD_COMBO                   1166
#define IDC_VCD_CONFIG                  1167
#define IDC_VCD_DATA_RATE_CAP           1168
#define IDC_VCD_DATA_RATE_EDIT          1169
#define IDC_VCD_DATA_RATE_UNIT          1170
#define IDC_VCD_KEY_FRAME_CAP           1171
#define IDC_VCD_KEY_FRAME_EDIT          1172
#define IDC_VCD_KEY_FRAME_UNIT          1173
#define IDC_VCD_P_FRAMES_CAP            1174
#define IDC_VCD_P_FRAMES_EDIT           1175
#define IDC_VCD_P_FRAMES_UNIT           1176
#define IDC_VCD_QUALITY                 1177
#define IDC_VCD_QUAL_CAP                1178
#define IDC_VCD_QUAL_NUM                1179
#define IDC_VCD_WND_SIZE_CAP            1180
#define IDC_VCD_WND_SIZE_EDIT           1181
#define IDC_VCD_WND_SIZE_UNIT           1182
#define IDC_XF_EDIT_A                   1183
#define IDC_XF_EDIT_B                   1184
#define IDC_XF_EDIT_MIX                 1185
#define IDC_XF_LOOP                     1186
#define IDC_XF_MIX_SAVE                 1187
#define IDC_XF_MIX_VIEW                 1188
#define IDC_XF_NAME_A                   1189
#define IDC_XF_NAME_B                   1190
#define IDC_XF_OPEN_A                   1191
#define IDC_XF_OPEN_B                   1192
#define IDC_XF_PLAY                     1193
#define IDC_XF_POS_EDIT                 1194
#define IDC_XF_POS_SLIDER               1195
#define IDC_XF_POS_SPIN                 1196
#define IDC_XF_SAVE_A                   1197
#define IDC_XF_SAVE_B                   1198
#define IDC_XF_SECS_EDIT                1199
#define IDC_XF_SECS_SPIN                1200
#define IDC_XF_STOP                     1201
#define IDC_XF_WAVEFORM                 1202
#define ID_APP_HOME_PAGE                32771
#define ID_EDIT_DOCUMENT                32772
#define ID_EDIT_END                     32773
#define ID_EDIT_GLOBAL_PARMS            32774
#define ID_EDIT_HOME                    32775
#define ID_EDIT_MASTER_OFFSETS          32776
#define ID_EDIT_NEXT_PATCH_TO_A         32777
#define ID_EDIT_NEXT_PATCH_TO_B         32778
#define ID_EDIT_PAGE_DOWN               32779
#define ID_EDIT_PAGE_UP                 32780
#define ID_EDIT_PATCH_FULL              32781
#define ID_EDIT_PATCH_GEOMETRY          32782
#define ID_EDIT_RANDOM_PATCH            32783
#define ID_EDIT_XFADER_A                32784
#define ID_EDIT_XFADER_B                32785
#define ID_EDIT_XFADER_MIX              32786
#define ID_EDIT_XFADE_LOOP              32787
#define ID_EDIT_XFADE_PLAY              32788
#define ID_EDIT_XFADE_TIME_DOWN         32789
#define ID_EDIT_XFADE_TIME_UP           32790
#define ID_EDIT_ZERO_CONTROLLERS        32791
#define ID_FILE_EXPORT_BITMAP           32792
#define ID_FILE_LOAD_SNAPSHOT           32793
#define ID_FILE_MOVIE_EXPORT            32794
#define ID_FILE_MOVIE_PLAY              32795
#define ID_FILE_MOVIE_RECORD            32796
#define ID_FILE_MOVIE_RESIZE            32797
#define ID_FILE_SAVE_MIX                32798
#define ID_FILE_TAKE_SNAPSHOT           32799
#define ID_IMG_BACKWARDS                32800
#define ID_IMG_CENTER_ORIGIN            32801
#define ID_IMG_CONVEX                   32802
#define ID_IMG_DAMPING_DOWN             32803
#define ID_IMG_DAMPING_UP               32804
#define ID_IMG_DRAG_ORIGIN              32805
#define ID_IMG_FILL                     32806
#define ID_IMG_INVERT_COLOR             32807
#define ID_IMG_INVERT_FILL              32808
#define ID_IMG_INVERT_OUTLINE           32809
#define ID_IMG_INVERT_XRAY              32810
#define ID_IMG_LOOP_HUE                 32811
#define ID_IMG_MIRROR                   32812
#define ID_IMG_OUTLINE                  32813
#define ID_IMG_RANDOM_ORIGIN            32814
#define ID_IMG_RANDOM_PHASE             32815
#define ID_IMG_REVERSE                  32816
#define ID_IMG_ROTATE_HUE               32817
#define ID_IMG_SET_ORIGIN               32818
#define ID_IMG_STEP_BACKWARD            32819
#define ID_IMG_STEP_FORWARD             32820
#define ID_IMG_TOGGLE_ORIGIN            32821
#define ID_IMG_VIDEO_AUTO_REWIND        32822
#define ID_IMG_VIDEO_CYCLE              32823
#define ID_IMG_VIDEO_CYCLE_LEN0         32824
#define ID_IMG_VIDEO_CYCLE_LEN1         32825
#define ID_IMG_VIDEO_CYCLE_LEN2         32826
#define ID_IMG_VIDEO_CYCLE_LEN3         32827
#define ID_IMG_VIDEO_CYCLE_LEN4         32828
#define ID_IMG_VIDEO_CYCLE_LEN5         32829
#define ID_IMG_VIDEO_CYCLE_LEN6         32830
#define ID_IMG_VIDEO_CYCLE_LEN7         32831
#define ID_IMG_VIDEO_CYCLE_LEN8         32832
#define ID_IMG_VIDEO_CYCLE_LEN9         32833
#define ID_IMG_VIDEO_RANDOM_ORIGIN      32834
#define ID_IMG_VIDEO_ROP0               32835
#define ID_IMG_VIDEO_ROP1               32836
#define ID_IMG_VIDEO_ROP2               32837
#define ID_IMG_VIDEO_ROP3               32838
#define ID_IMG_VIDEO_ROP4               32839
#define ID_IMG_VIDEO_ROP5               32840
#define ID_IMG_VIDEO_ROP6               32841
#define ID_IMG_VIDEO_ROP7               32842
#define ID_IMG_VIDEO_ROP8               32843
#define ID_IMG_VIDEO_ROP9               32844
#define ID_IMG_VIDEO_SELECT0            32845
#define ID_IMG_VIDEO_SELECT1            32846
#define ID_IMG_VIDEO_SELECT2            32847
#define ID_IMG_VIDEO_SELECT3            32848
#define ID_IMG_VIDEO_SELECT4            32849
#define ID_IMG_VIDEO_SELECT5            32850
#define ID_IMG_VIDEO_SELECT6            32851
#define ID_IMG_VIDEO_SELECT7            32852
#define ID_IMG_VIDEO_SELECT8            32853
#define ID_IMG_VIDEO_SELECT9            32854
#define ID_IMG_VIDEO_SELECT_NONE        32855
#define ID_IMG_XRAY                     32856
#define ID_INDICATOR_AUTOPLAY           32857
#define ID_INDICATOR_FRAME_RATE         32858
#define ID_INDICATOR_HUE_LOOP           32859
#define ID_INDICATOR_MIX                32860
#define ID_INDICATOR_ORG_MOTION         32861
#define ID_INDICATOR_PATCH_MODE         32862
#define ID_INDICATOR_PAUSE              32863
#define ID_INDICATOR_RECORD             32864
#define ID_INDICATOR_TEMPO              32865
#define ID_PL_EDIT_AUTO_ASSIGN          32866
#define ID_PL_EDIT_COPY                 32867
#define ID_PL_EDIT_CUT                  32868
#define ID_PL_EDIT_DELETE               32869
#define ID_PL_EDIT_FADE_TO              32870
#define ID_PL_EDIT_MIDI_MAPPING         32871
#define ID_PL_EDIT_PASTE                32872
#define ID_PL_EDIT_REMOVE_KEY           32873
#define ID_PL_EDIT_SELECT_ALL           32874
#define ID_PL_EDIT_SEND_TO_A            32875
#define ID_PL_EDIT_SEND_TO_B            32876
#define ID_PL_EDIT_SEND_TO_DOC          32877
#define ID_PL_FILE_EXPORT_THUMBS        32878
#define ID_PL_FILE_IMPORT_MIDI          32879
#define ID_PL_FILE_IMPORT_MIDI_SETUP    32880
#define ID_PL_FILE_INSERT_PATCHES       32881
#define ID_PL_FILE_MRU_FILE1            32882
#define ID_PL_FILE_MRU_FILE2            32883
#define ID_PL_FILE_MRU_FILE3            32884
#define ID_PL_FILE_MRU_FILE4            32885
#define ID_PL_FILE_NEW                  32886
#define ID_PL_FILE_OPEN                 32887
#define ID_PL_FILE_SAVE                 32888
#define ID_PL_FILE_SAVE_AS              32889
#define ID_PL_VIEW_REFRESH_THUMBS       32890
#define ID_PL_VIEW_THUMB_SIZE0          32891
#define ID_PL_VIEW_THUMB_SIZE1          32892
#define ID_PL_VIEW_THUMB_SIZE2          32893
#define ID_PL_VIEW_THUMB_SIZE3          32894
#define ID_PL_VIEW_THUMB_SIZE4          32895
#define ID_PL_VIEW_TYPE_DETAILS         32896
#define ID_PL_VIEW_TYPE_THUMBS          32897
#define ID_SNAP_EXPORT_ALL              32898
#define ID_SNAP_SLIDE_SHOW              32899
#define ID_TEMPO_DOUBLE                 32900
#define ID_TEMPO_HALF                   32901
#define ID_TEMPO_NUDGE_DOWN             32902
#define ID_TEMPO_NUDGE_UP               32903
#define ID_TEMPO_RESYNC                 32904
#define ID_VIEW_AUTOPLAY                32905
#define ID_VIEW_CROSSFADER              32906
#define ID_VIEW_DEMO                    32907
#define ID_VIEW_MASTER                  32908
#define ID_VIEW_MIDI_SETUP              32909
#define ID_VIEW_MIX                     32910
#define ID_VIEW_NUMBERS                 32911
#define ID_VIEW_OPTIONS                 32912
#define ID_VIEW_PARMS                   32913
#define ID_VIEW_PLAYLIST                32914
#define ID_WND_CLEAR                    32915
#define ID_WND_DETACH                   32916
#define ID_WND_FULL_SCREEN              32917
#define ID_WND_PANIC                    32918
#define ID_WND_PAUSE                    32919
#define ID_WND_STEP                     32920
#define ID_WND_VEEJAY                   32921
#define ID_WND_ZOOM_CENTER              32922

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        413
#define _APS_NEXT_COMMAND_VALUE         32923
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
