// Copyleft 2005 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
        chris korda
 
		revision history:
		rev		date	comments
        00      04sep05	initial version
        01      05oct13	add undef
        02      04jun18	add GM patch and drum names
        03      05jan19	add controller titles
		04		19mar20	add channel voice and system status messages

        MIDI controller definitions
 
*/

#ifdef MIDICHANSTATDEF

MIDICHANSTATDEF(NOTE_OFF)		// 0x80
MIDICHANSTATDEF(NOTE_ON)		// 0x90
MIDICHANSTATDEF(KEY_AFT)		// 0xa0
MIDICHANSTATDEF(CONTROL)		// 0xb0
MIDICHANSTATDEF(PATCH)			// 0xc0
MIDICHANSTATDEF(CHAN_AFT)		// 0xe0
MIDICHANSTATDEF(WHEEL)			// 0xd0

#undef MIDICHANSTATDEF
#endif

#ifdef MIDISYSSTATDEF

MIDISYSSTATDEF(SYSEX)			// 0xf0
MIDISYSSTATDEF(MTC_QTR_FRAME)	// 0xf1
MIDISYSSTATDEF(SONG_POSITION)	// 0xf2
MIDISYSSTATDEF(SONG_SELECT)		// 0xf3
MIDISYSSTATDEF(UNDEFINED_1)		// 0xf4
MIDISYSSTATDEF(UNDEFINED_2)		// 0xf5
MIDISYSSTATDEF(TUNE_REQUEST)	// 0xf6
MIDISYSSTATDEF(EOX)				// 0xf7
MIDISYSSTATDEF(CLOCK)			// 0xf8
MIDISYSSTATDEF(UNDEFINED_3)		// 0xf9
MIDISYSSTATDEF(START)			// 0xfa
MIDISYSSTATDEF(CONTINUE)		// 0xfb
MIDISYSSTATDEF(STOP)			// 0xfc
MIDISYSSTATDEF(UNDEFINED_4)		// 0xfd
MIDISYSSTATDEF(ACTIVE_SENSING)	// 0xfe
MIDISYSSTATDEF(SYSTEM_RESET)	// 0xff

#undef MIDISYSSTATDEF
#endif

#ifdef MIDI_CTRLR_DEF

MIDI_CTRLR_DEF(/*   0 */ BANK_SELECT)
MIDI_CTRLR_DEF(/*   1 */ MODULATION_WHEEL)
MIDI_CTRLR_DEF(/*   2 */ BREATH_CONTROLLER)
MIDI_CTRLR_DEF(/*   3 */ UNDEFINED_1)
MIDI_CTRLR_DEF(/*   4 */ FOOT_CONTROLLER)
MIDI_CTRLR_DEF(/*   5 */ PORTAMENTO_TIME)
MIDI_CTRLR_DEF(/*   6 */ DATA_ENTRY_MSB)
MIDI_CTRLR_DEF(/*   7 */ VOLUME)
MIDI_CTRLR_DEF(/*   8 */ BALANCE)
MIDI_CTRLR_DEF(/*   9 */ UNDEFINED_2)
MIDI_CTRLR_DEF(/*  10 */ PAN)
MIDI_CTRLR_DEF(/*  11 */ EXPRESSION_CONTROLLER)
MIDI_CTRLR_DEF(/*  12 */ EFFECT_1)
MIDI_CTRLR_DEF(/*  13 */ EFFECT_2)
MIDI_CTRLR_DEF(/*  14 */ UNDEFINED_3)
MIDI_CTRLR_DEF(/*  15 */ UNDEFINED_4)
MIDI_CTRLR_DEF(/*  16 */ GENERAL_PURPOSE_CONTROLLER_1)
MIDI_CTRLR_DEF(/*  17 */ GENERAL_PURPOSE_CONTROLLER_2)
MIDI_CTRLR_DEF(/*  18 */ GENERAL_PURPOSE_CONTROLLER_3)
MIDI_CTRLR_DEF(/*  19 */ GENERAL_PURPOSE_CONTROLLER_4)
MIDI_CTRLR_DEF(/*  20 */ UNDEFINED_5)
MIDI_CTRLR_DEF(/*  21 */ UNDEFINED_6)
MIDI_CTRLR_DEF(/*  22 */ UNDEFINED_7)
MIDI_CTRLR_DEF(/*  23 */ UNDEFINED_8)
MIDI_CTRLR_DEF(/*  24 */ UNDEFINED_9)
MIDI_CTRLR_DEF(/*  25 */ UNDEFINED_10)
MIDI_CTRLR_DEF(/*  26 */ UNDEFINED_11)
MIDI_CTRLR_DEF(/*  27 */ UNDEFINED_12)
MIDI_CTRLR_DEF(/*  28 */ UNDEFINED_13)
MIDI_CTRLR_DEF(/*  29 */ UNDEFINED_14)
MIDI_CTRLR_DEF(/*  30 */ UNDEFINED_15)
MIDI_CTRLR_DEF(/*  31 */ UNDEFINED_16)
MIDI_CTRLR_DEF(/*  32 */ BANK_SELECT_LSB)
MIDI_CTRLR_DEF(/*  33 */ MODULATION_WHEEL_LSB)
MIDI_CTRLR_DEF(/*  34 */ BREATH_CONTROLLER_LSB)
MIDI_CTRLR_DEF(/*  35 */ UNDEFINED_17)
MIDI_CTRLR_DEF(/*  36 */ FOOT_PEDAL_LSB)
MIDI_CTRLR_DEF(/*  37 */ PORTAMENTO_TIME_LSB)
MIDI_CTRLR_DEF(/*  38 */ DATA_ENTRY_LSB)
MIDI_CTRLR_DEF(/*  39 */ VOLUME_LSB)
MIDI_CTRLR_DEF(/*  40 */ BALANCE_LSB)
MIDI_CTRLR_DEF(/*  41 */ UNDEFINED_18)
MIDI_CTRLR_DEF(/*  42 */ PAN_LSB)
MIDI_CTRLR_DEF(/*  43 */ EXPRESSION_LSB)
MIDI_CTRLR_DEF(/*  44 */ EFFECT_CONTROL_1_LSB)
MIDI_CTRLR_DEF(/*  45 */ EFFECT_CONTROL_2_LSB)
MIDI_CTRLR_DEF(/*  46 */ UNDEFINED_19)
MIDI_CTRLR_DEF(/*  47 */ UNDEFINED_20)
MIDI_CTRLR_DEF(/*  48 */ UNDEFINED_21)
MIDI_CTRLR_DEF(/*  49 */ UNDEFINED_22)
MIDI_CTRLR_DEF(/*  50 */ UNDEFINED_23)
MIDI_CTRLR_DEF(/*  51 */ UNDEFINED_24)
MIDI_CTRLR_DEF(/*  52 */ UNDEFINED_25)
MIDI_CTRLR_DEF(/*  53 */ UNDEFINED_26)
MIDI_CTRLR_DEF(/*  54 */ UNDEFINED_27)
MIDI_CTRLR_DEF(/*  55 */ UNDEFINED_28)
MIDI_CTRLR_DEF(/*  56 */ UNDEFINED_29)
MIDI_CTRLR_DEF(/*  57 */ UNDEFINED_30)
MIDI_CTRLR_DEF(/*  58 */ UNDEFINED_31)
MIDI_CTRLR_DEF(/*  59 */ UNDEFINED_32)
MIDI_CTRLR_DEF(/*  60 */ UNDEFINED_33)
MIDI_CTRLR_DEF(/*  61 */ UNDEFINED_34)
MIDI_CTRLR_DEF(/*  62 */ UNDEFINED_35)
MIDI_CTRLR_DEF(/*  63 */ UNDEFINED_36)
MIDI_CTRLR_DEF(/*  64 */ DAMPER_PEDAL)
MIDI_CTRLR_DEF(/*  65 */ PORTAMENTO)
MIDI_CTRLR_DEF(/*  66 */ SUSTENUTO_PEDAL)
MIDI_CTRLR_DEF(/*  67 */ SOFT_PEDAL)
MIDI_CTRLR_DEF(/*  68 */ LEGATO_PEDAL)
MIDI_CTRLR_DEF(/*  69 */ HOLD_2_PEDAL)
MIDI_CTRLR_DEF(/*  70 */ SOUND_VARIATION)
MIDI_CTRLR_DEF(/*  71 */ SOUND_TIMBRE)
MIDI_CTRLR_DEF(/*  72 */ SOUND_RELEASE_TIME)
MIDI_CTRLR_DEF(/*  73 */ SOUND_ATTACK_TIME)
MIDI_CTRLR_DEF(/*  74 */ SOUND_BRIGHTNESS)
MIDI_CTRLR_DEF(/*  75 */ SOUND_CONTROL_6)
MIDI_CTRLR_DEF(/*  76 */ SOUND_CONTROL_7)
MIDI_CTRLR_DEF(/*  77 */ SOUND_CONTROL_8)
MIDI_CTRLR_DEF(/*  78 */ SOUND_CONTROL_9)
MIDI_CTRLR_DEF(/*  79 */ SOUND_CONTROL_10)
MIDI_CTRLR_DEF(/*  80 */ GENERAL_PURPOSE_BUTTON_1)
MIDI_CTRLR_DEF(/*  81 */ GENERAL_PURPOSE_BUTTON_2)
MIDI_CTRLR_DEF(/*  82 */ GENERAL_PURPOSE_BUTTON_3)
MIDI_CTRLR_DEF(/*  83 */ GENERAL_PURPOSE_BUTTON_4)
MIDI_CTRLR_DEF(/*  84 */ UNDEFINED_37)
MIDI_CTRLR_DEF(/*  85 */ UNDEFINED_38)
MIDI_CTRLR_DEF(/*  86 */ UNDEFINED_39)
MIDI_CTRLR_DEF(/*  87 */ UNDEFINED_40)
MIDI_CTRLR_DEF(/*  88 */ UNDEFINED_41)
MIDI_CTRLR_DEF(/*  89 */ UNDEFINED_42)
MIDI_CTRLR_DEF(/*  90 */ UNDEFINED_43)
MIDI_CTRLR_DEF(/*  91 */ REVERB_LEVEL)
MIDI_CTRLR_DEF(/*  92 */ TREMOLO_LEVEL)
MIDI_CTRLR_DEF(/*  93 */ CHORUS_LEVEL)
MIDI_CTRLR_DEF(/*  94 */ CELESTE_LEVEL)
MIDI_CTRLR_DEF(/*  95 */ PHASER_LEVEL)
MIDI_CTRLR_DEF(/*  96 */ DATA_INCREMENT)
MIDI_CTRLR_DEF(/*  97 */ DATA_DECREMENT)
MIDI_CTRLR_DEF(/*  98 */ NRPN_LSB)
MIDI_CTRLR_DEF(/*  99 */ NRPN_MSB)
MIDI_CTRLR_DEF(/* 100 */ RPN_LSB)
MIDI_CTRLR_DEF(/* 101 */ RPN_MSB)
MIDI_CTRLR_DEF(/* 102 */ UNDEFINED_44)
MIDI_CTRLR_DEF(/* 103 */ UNDEFINED_45)
MIDI_CTRLR_DEF(/* 104 */ UNDEFINED_46)
MIDI_CTRLR_DEF(/* 105 */ UNDEFINED_47)
MIDI_CTRLR_DEF(/* 106 */ UNDEFINED_48)
MIDI_CTRLR_DEF(/* 107 */ UNDEFINED_49)
MIDI_CTRLR_DEF(/* 108 */ UNDEFINED_50)
MIDI_CTRLR_DEF(/* 109 */ UNDEFINED_51)
MIDI_CTRLR_DEF(/* 110 */ UNDEFINED_52)
MIDI_CTRLR_DEF(/* 111 */ UNDEFINED_53)
MIDI_CTRLR_DEF(/* 112 */ UNDEFINED_54)
MIDI_CTRLR_DEF(/* 113 */ UNDEFINED_55)
MIDI_CTRLR_DEF(/* 114 */ UNDEFINED_56)
MIDI_CTRLR_DEF(/* 115 */ UNDEFINED_57)
MIDI_CTRLR_DEF(/* 116 */ UNDEFINED_58)
MIDI_CTRLR_DEF(/* 117 */ UNDEFINED_59)
MIDI_CTRLR_DEF(/* 118 */ UNDEFINED_60)
MIDI_CTRLR_DEF(/* 119 */ UNDEFINED_61)
MIDI_CTRLR_DEF(/* 120 */ ALL_SOUND_OFF)
MIDI_CTRLR_DEF(/* 121 */ ALL_CONTROLLERS_OFF)
MIDI_CTRLR_DEF(/* 122 */ LOCAL_CONTROL)
MIDI_CTRLR_DEF(/* 123 */ ALL_NOTES_OFF)
MIDI_CTRLR_DEF(/* 124 */ OMNI_MODE_OFF)
MIDI_CTRLR_DEF(/* 125 */ OMNI_MODE_ON)
MIDI_CTRLR_DEF(/* 126 */ MONO_OPERATION)
MIDI_CTRLR_DEF(/* 127 */ POLY_OPERATION)

#endif	// MIDI_CTRLR_DEF
#undef MIDI_CTRLR_DEF

#ifdef MIDI_CTRLR_TITLE_DEF

MIDI_CTRLR_TITLE_DEF(/*   0 */ "Bank Select")
MIDI_CTRLR_TITLE_DEF(/*   1 */ "Modulation Wheel")
MIDI_CTRLR_TITLE_DEF(/*   2 */ "Breath Controller")
MIDI_CTRLR_TITLE_DEF(/*   3 */ "Undefined 1")
MIDI_CTRLR_TITLE_DEF(/*   4 */ "Foot Controller")
MIDI_CTRLR_TITLE_DEF(/*   5 */ "Portamento Time")
MIDI_CTRLR_TITLE_DEF(/*   6 */ "Data Entry Msb")
MIDI_CTRLR_TITLE_DEF(/*   7 */ "Volume")
MIDI_CTRLR_TITLE_DEF(/*   8 */ "Balance")
MIDI_CTRLR_TITLE_DEF(/*   9 */ "Undefined 2")
MIDI_CTRLR_TITLE_DEF(/*  10 */ "Pan")
MIDI_CTRLR_TITLE_DEF(/*  11 */ "Expression Controller")
MIDI_CTRLR_TITLE_DEF(/*  12 */ "Effect 1")
MIDI_CTRLR_TITLE_DEF(/*  13 */ "Effect 2")
MIDI_CTRLR_TITLE_DEF(/*  14 */ "Undefined 3")
MIDI_CTRLR_TITLE_DEF(/*  15 */ "Undefined 4")
MIDI_CTRLR_TITLE_DEF(/*  16 */ "General Purpose Controller 1")
MIDI_CTRLR_TITLE_DEF(/*  17 */ "General Purpose Controller 2")
MIDI_CTRLR_TITLE_DEF(/*  18 */ "General Purpose Controller 3")
MIDI_CTRLR_TITLE_DEF(/*  19 */ "General Purpose Controller 4")
MIDI_CTRLR_TITLE_DEF(/*  20 */ "Undefined 5")
MIDI_CTRLR_TITLE_DEF(/*  21 */ "Undefined 6")
MIDI_CTRLR_TITLE_DEF(/*  22 */ "Undefined 7")
MIDI_CTRLR_TITLE_DEF(/*  23 */ "Undefined 8")
MIDI_CTRLR_TITLE_DEF(/*  24 */ "Undefined 9")
MIDI_CTRLR_TITLE_DEF(/*  25 */ "Undefined 10")
MIDI_CTRLR_TITLE_DEF(/*  26 */ "Undefined 11")
MIDI_CTRLR_TITLE_DEF(/*  27 */ "Undefined 12")
MIDI_CTRLR_TITLE_DEF(/*  28 */ "Undefined 13")
MIDI_CTRLR_TITLE_DEF(/*  29 */ "Undefined 14")
MIDI_CTRLR_TITLE_DEF(/*  30 */ "Undefined 15")
MIDI_CTRLR_TITLE_DEF(/*  31 */ "Undefined 16")
MIDI_CTRLR_TITLE_DEF(/*  32 */ "Bank Select Lsb")
MIDI_CTRLR_TITLE_DEF(/*  33 */ "Modulation Wheel Lsb")
MIDI_CTRLR_TITLE_DEF(/*  34 */ "Breath Controller Lsb")
MIDI_CTRLR_TITLE_DEF(/*  35 */ "Undefined 17")
MIDI_CTRLR_TITLE_DEF(/*  36 */ "Foot Pedal Lsb")
MIDI_CTRLR_TITLE_DEF(/*  37 */ "Portamento Time Lsb")
MIDI_CTRLR_TITLE_DEF(/*  38 */ "Data Entry Lsb")
MIDI_CTRLR_TITLE_DEF(/*  39 */ "Volume Lsb")
MIDI_CTRLR_TITLE_DEF(/*  40 */ "Balance Lsb")
MIDI_CTRLR_TITLE_DEF(/*  41 */ "Undefined 18")
MIDI_CTRLR_TITLE_DEF(/*  42 */ "Pan Lsb")
MIDI_CTRLR_TITLE_DEF(/*  43 */ "Expression Lsb")
MIDI_CTRLR_TITLE_DEF(/*  44 */ "Effect Control 1 Lsb")
MIDI_CTRLR_TITLE_DEF(/*  45 */ "Effect Control 2 Lsb")
MIDI_CTRLR_TITLE_DEF(/*  46 */ "Undefined 19")
MIDI_CTRLR_TITLE_DEF(/*  47 */ "Undefined 20")
MIDI_CTRLR_TITLE_DEF(/*  48 */ "Undefined 21")
MIDI_CTRLR_TITLE_DEF(/*  49 */ "Undefined 22")
MIDI_CTRLR_TITLE_DEF(/*  50 */ "Undefined 23")
MIDI_CTRLR_TITLE_DEF(/*  51 */ "Undefined 24")
MIDI_CTRLR_TITLE_DEF(/*  52 */ "Undefined 25")
MIDI_CTRLR_TITLE_DEF(/*  53 */ "Undefined 26")
MIDI_CTRLR_TITLE_DEF(/*  54 */ "Undefined 27")
MIDI_CTRLR_TITLE_DEF(/*  55 */ "Undefined 28")
MIDI_CTRLR_TITLE_DEF(/*  56 */ "Undefined 29")
MIDI_CTRLR_TITLE_DEF(/*  57 */ "Undefined 30")
MIDI_CTRLR_TITLE_DEF(/*  58 */ "Undefined 31")
MIDI_CTRLR_TITLE_DEF(/*  59 */ "Undefined 32")
MIDI_CTRLR_TITLE_DEF(/*  60 */ "Undefined 33")
MIDI_CTRLR_TITLE_DEF(/*  61 */ "Undefined 34")
MIDI_CTRLR_TITLE_DEF(/*  62 */ "Undefined 35")
MIDI_CTRLR_TITLE_DEF(/*  63 */ "Undefined 36")
MIDI_CTRLR_TITLE_DEF(/*  64 */ "Damper Pedal")
MIDI_CTRLR_TITLE_DEF(/*  65 */ "Portamento")
MIDI_CTRLR_TITLE_DEF(/*  66 */ "Sustenuto Pedal")
MIDI_CTRLR_TITLE_DEF(/*  67 */ "Soft Pedal")
MIDI_CTRLR_TITLE_DEF(/*  68 */ "Legato Pedal")
MIDI_CTRLR_TITLE_DEF(/*  69 */ "Hold 2 Pedal")
MIDI_CTRLR_TITLE_DEF(/*  70 */ "Sound Variation")
MIDI_CTRLR_TITLE_DEF(/*  71 */ "Sound Timbre")
MIDI_CTRLR_TITLE_DEF(/*  72 */ "Sound Release Time")
MIDI_CTRLR_TITLE_DEF(/*  73 */ "Sound Attack Time")
MIDI_CTRLR_TITLE_DEF(/*  74 */ "Sound Brightness")
MIDI_CTRLR_TITLE_DEF(/*  75 */ "Sound Control 6")
MIDI_CTRLR_TITLE_DEF(/*  76 */ "Sound Control 7")
MIDI_CTRLR_TITLE_DEF(/*  77 */ "Sound Control 8")
MIDI_CTRLR_TITLE_DEF(/*  78 */ "Sound Control 9")
MIDI_CTRLR_TITLE_DEF(/*  79 */ "Sound Control 10")
MIDI_CTRLR_TITLE_DEF(/*  80 */ "General Purpose Button 1")
MIDI_CTRLR_TITLE_DEF(/*  81 */ "General Purpose Button 2")
MIDI_CTRLR_TITLE_DEF(/*  82 */ "General Purpose Button 3")
MIDI_CTRLR_TITLE_DEF(/*  83 */ "General Purpose Button 4")
MIDI_CTRLR_TITLE_DEF(/*  84 */ "Undefined 37")
MIDI_CTRLR_TITLE_DEF(/*  85 */ "Undefined 38")
MIDI_CTRLR_TITLE_DEF(/*  86 */ "Undefined 39")
MIDI_CTRLR_TITLE_DEF(/*  87 */ "Undefined 40")
MIDI_CTRLR_TITLE_DEF(/*  88 */ "Undefined 41")
MIDI_CTRLR_TITLE_DEF(/*  89 */ "Undefined 42")
MIDI_CTRLR_TITLE_DEF(/*  90 */ "Undefined 43")
MIDI_CTRLR_TITLE_DEF(/*  91 */ "Reverb Level")
MIDI_CTRLR_TITLE_DEF(/*  92 */ "Tremolo Level")
MIDI_CTRLR_TITLE_DEF(/*  93 */ "Chorus Level")
MIDI_CTRLR_TITLE_DEF(/*  94 */ "Celeste Level")
MIDI_CTRLR_TITLE_DEF(/*  95 */ "Phaser Level")
MIDI_CTRLR_TITLE_DEF(/*  96 */ "Data Increment")
MIDI_CTRLR_TITLE_DEF(/*  97 */ "Data Decrement")
MIDI_CTRLR_TITLE_DEF(/*  98 */ "Nrpn Lsb")
MIDI_CTRLR_TITLE_DEF(/*  99 */ "Nrpn Msb")
MIDI_CTRLR_TITLE_DEF(/* 100 */ "Rpn Lsb")
MIDI_CTRLR_TITLE_DEF(/* 101 */ "Rpn Msb")
MIDI_CTRLR_TITLE_DEF(/* 102 */ "Undefined 44")
MIDI_CTRLR_TITLE_DEF(/* 103 */ "Undefined 45")
MIDI_CTRLR_TITLE_DEF(/* 104 */ "Undefined 46")
MIDI_CTRLR_TITLE_DEF(/* 105 */ "Undefined 47")
MIDI_CTRLR_TITLE_DEF(/* 106 */ "Undefined 48")
MIDI_CTRLR_TITLE_DEF(/* 107 */ "Undefined 49")
MIDI_CTRLR_TITLE_DEF(/* 108 */ "Undefined 50")
MIDI_CTRLR_TITLE_DEF(/* 109 */ "Undefined 51")
MIDI_CTRLR_TITLE_DEF(/* 110 */ "Undefined 52")
MIDI_CTRLR_TITLE_DEF(/* 111 */ "Undefined 53")
MIDI_CTRLR_TITLE_DEF(/* 112 */ "Undefined 54")
MIDI_CTRLR_TITLE_DEF(/* 113 */ "Undefined 55")
MIDI_CTRLR_TITLE_DEF(/* 114 */ "Undefined 56")
MIDI_CTRLR_TITLE_DEF(/* 115 */ "Undefined 57")
MIDI_CTRLR_TITLE_DEF(/* 116 */ "Undefined 58")
MIDI_CTRLR_TITLE_DEF(/* 117 */ "Undefined 59")
MIDI_CTRLR_TITLE_DEF(/* 118 */ "Undefined 60")
MIDI_CTRLR_TITLE_DEF(/* 119 */ "Undefined 61")
MIDI_CTRLR_TITLE_DEF(/* 120 */ "All Sound Off")
MIDI_CTRLR_TITLE_DEF(/* 121 */ "All Controllers Off")
MIDI_CTRLR_TITLE_DEF(/* 122 */ "Local Control")
MIDI_CTRLR_TITLE_DEF(/* 123 */ "All Notes Off")
MIDI_CTRLR_TITLE_DEF(/* 124 */ "Omni Mode Off")
MIDI_CTRLR_TITLE_DEF(/* 125 */ "Omni Mode On")
MIDI_CTRLR_TITLE_DEF(/* 126 */ "Mono Operation")
MIDI_CTRLR_TITLE_DEF(/* 127 */ "Poly Operation")

#endif	// MIDI_CTRLR_TITLE_DEF
#undef MIDI_CTRLR_TITLE_DEF

#ifdef MIDI_GM_PATCH_DEF

// General MIDI patches are one-origin by convention

MIDI_GM_PATCH_DEF(/*   1 */ "Acoustic Grand Piano")
MIDI_GM_PATCH_DEF(/*   2 */ "Bright Acoustic Piano")
MIDI_GM_PATCH_DEF(/*   3 */ "Electric Grand Piano")
MIDI_GM_PATCH_DEF(/*   4 */ "Honky-tonk Piano")
MIDI_GM_PATCH_DEF(/*   5 */ "Electric Piano 1")
MIDI_GM_PATCH_DEF(/*   6 */ "Electric Piano 2")
MIDI_GM_PATCH_DEF(/*   7 */ "Harpsichord")
MIDI_GM_PATCH_DEF(/*   8 */ "Clavi")
MIDI_GM_PATCH_DEF(/*   9 */ "Celesta")
MIDI_GM_PATCH_DEF(/*  10 */ "Glockenspiel")
MIDI_GM_PATCH_DEF(/*  11 */ "Music Box")
MIDI_GM_PATCH_DEF(/*  12 */ "Vibraphone")
MIDI_GM_PATCH_DEF(/*  13 */ "Marimba")
MIDI_GM_PATCH_DEF(/*  14 */ "Xylophone")
MIDI_GM_PATCH_DEF(/*  15 */ "Tubular Bells")
MIDI_GM_PATCH_DEF(/*  16 */ "Dulcimer")
MIDI_GM_PATCH_DEF(/*  17 */ "Drawbar Organ")
MIDI_GM_PATCH_DEF(/*  18 */ "Percussive Organ")
MIDI_GM_PATCH_DEF(/*  19 */ "Rock Organ")
MIDI_GM_PATCH_DEF(/*  20 */ "Church Organ")
MIDI_GM_PATCH_DEF(/*  21 */ "Reed Organ")
MIDI_GM_PATCH_DEF(/*  22 */ "Accordion")
MIDI_GM_PATCH_DEF(/*  23 */ "Harmonica")
MIDI_GM_PATCH_DEF(/*  24 */ "Tango Accordion")
MIDI_GM_PATCH_DEF(/*  25 */ "Acoustic Guitar (nylon)")
MIDI_GM_PATCH_DEF(/*  26 */ "Acoustic Guitar (steel)")
MIDI_GM_PATCH_DEF(/*  27 */ "Electric Guitar (jazz)")
MIDI_GM_PATCH_DEF(/*  28 */ "Electric Guitar (clean)")
MIDI_GM_PATCH_DEF(/*  29 */ "Electric Guitar (muted)")
MIDI_GM_PATCH_DEF(/*  30 */ "Overdriven Guitar")
MIDI_GM_PATCH_DEF(/*  31 */ "Distortion Guitar")
MIDI_GM_PATCH_DEF(/*  32 */ "Guitar harmonics")
MIDI_GM_PATCH_DEF(/*  33 */ "Acoustic Bass")
MIDI_GM_PATCH_DEF(/*  34 */ "Electric Bass (finger)")
MIDI_GM_PATCH_DEF(/*  35 */ "Electric Bass (pick)")
MIDI_GM_PATCH_DEF(/*  36 */ "Fretless Bass")
MIDI_GM_PATCH_DEF(/*  37 */ "Slap Bass 1")
MIDI_GM_PATCH_DEF(/*  38 */ "Slap Bass 2")
MIDI_GM_PATCH_DEF(/*  39 */ "Synth Bass 1")
MIDI_GM_PATCH_DEF(/*  40 */ "Synth Bass 2")
MIDI_GM_PATCH_DEF(/*  41 */ "Violin")
MIDI_GM_PATCH_DEF(/*  42 */ "Viola")
MIDI_GM_PATCH_DEF(/*  43 */ "Cello")
MIDI_GM_PATCH_DEF(/*  44 */ "Contrabass")
MIDI_GM_PATCH_DEF(/*  45 */ "Tremolo Strings")
MIDI_GM_PATCH_DEF(/*  46 */ "Pizzicato Strings")
MIDI_GM_PATCH_DEF(/*  47 */ "Orchestral Harp")
MIDI_GM_PATCH_DEF(/*  48 */ "Timpani")
MIDI_GM_PATCH_DEF(/*  49 */ "String Ensemble 1")
MIDI_GM_PATCH_DEF(/*  50 */ "String Ensemble 2")
MIDI_GM_PATCH_DEF(/*  51 */ "SynthStrings 1")
MIDI_GM_PATCH_DEF(/*  52 */ "SynthStrings 2")
MIDI_GM_PATCH_DEF(/*  53 */ "Choir Aahs")
MIDI_GM_PATCH_DEF(/*  54 */ "Voice Oohs")
MIDI_GM_PATCH_DEF(/*  55 */ "Synth Voice")
MIDI_GM_PATCH_DEF(/*  56 */ "Orchestra Hit")
MIDI_GM_PATCH_DEF(/*  57 */ "Trumpet")
MIDI_GM_PATCH_DEF(/*  58 */ "Trombone")
MIDI_GM_PATCH_DEF(/*  59 */ "Tuba")
MIDI_GM_PATCH_DEF(/*  60 */ "Muted Trumpet")
MIDI_GM_PATCH_DEF(/*  61 */ "French Horn")
MIDI_GM_PATCH_DEF(/*  62 */ "Brass Section")
MIDI_GM_PATCH_DEF(/*  63 */ "SynthBrass 1")
MIDI_GM_PATCH_DEF(/*  64 */ "SynthBrass 2")
MIDI_GM_PATCH_DEF(/*  65 */ "Soprano Sax")
MIDI_GM_PATCH_DEF(/*  66 */ "Alto Sax")
MIDI_GM_PATCH_DEF(/*  67 */ "Tenor Sax")
MIDI_GM_PATCH_DEF(/*  68 */ "Baritone Sax")
MIDI_GM_PATCH_DEF(/*  69 */ "Oboe")
MIDI_GM_PATCH_DEF(/*  70 */ "English Horn")
MIDI_GM_PATCH_DEF(/*  71 */ "Bassoon")
MIDI_GM_PATCH_DEF(/*  72 */ "Clarinet")
MIDI_GM_PATCH_DEF(/*  73 */ "Piccolo")
MIDI_GM_PATCH_DEF(/*  74 */ "Flute")
MIDI_GM_PATCH_DEF(/*  75 */ "Recorder")
MIDI_GM_PATCH_DEF(/*  76 */ "Pan Flute")
MIDI_GM_PATCH_DEF(/*  77 */ "Blown Bottle")
MIDI_GM_PATCH_DEF(/*  78 */ "Shakuhachi")
MIDI_GM_PATCH_DEF(/*  79 */ "Whistle")
MIDI_GM_PATCH_DEF(/*  80 */ "Ocarina")
MIDI_GM_PATCH_DEF(/*  81 */ "Lead 1 (square)")
MIDI_GM_PATCH_DEF(/*  82 */ "Lead 2 (sawtooth)")
MIDI_GM_PATCH_DEF(/*  83 */ "Lead 3 (calliope)")
MIDI_GM_PATCH_DEF(/*  84 */ "Lead 4 (chiff)")
MIDI_GM_PATCH_DEF(/*  85 */ "Lead 5 (charang)")
MIDI_GM_PATCH_DEF(/*  86 */ "Lead 6 (voice)")
MIDI_GM_PATCH_DEF(/*  87 */ "Lead 7 (fifths)")
MIDI_GM_PATCH_DEF(/*  88 */ "Lead 8 (bass + lead)")
MIDI_GM_PATCH_DEF(/*  89 */ "Pad 1 (new age)")
MIDI_GM_PATCH_DEF(/*  90 */ "Pad 2 (warm)")
MIDI_GM_PATCH_DEF(/*  91 */ "Pad 3 (polysynth)")
MIDI_GM_PATCH_DEF(/*  92 */ "Pad 4 (choir)")
MIDI_GM_PATCH_DEF(/*  93 */ "Pad 5 (bowed)")
MIDI_GM_PATCH_DEF(/*  94 */ "Pad 6 (metallic)")
MIDI_GM_PATCH_DEF(/*  95 */ "Pad 7 (halo)")
MIDI_GM_PATCH_DEF(/*  96 */ "Pad 8 (sweep)")
MIDI_GM_PATCH_DEF(/*  97 */ "FX 1 (rain)")
MIDI_GM_PATCH_DEF(/*  98 */ "FX 2 (soundtrack)")
MIDI_GM_PATCH_DEF(/*  99 */ "FX 3 (crystal)")
MIDI_GM_PATCH_DEF(/* 100 */ "FX 4 (atmosphere)")
MIDI_GM_PATCH_DEF(/* 101 */ "FX 5 (brightness)")
MIDI_GM_PATCH_DEF(/* 102 */ "FX 6 (goblins)")
MIDI_GM_PATCH_DEF(/* 103 */ "FX 7 (echoes)")
MIDI_GM_PATCH_DEF(/* 104 */ "FX 8 (sci-fi)")
MIDI_GM_PATCH_DEF(/* 105 */ "Sitar")
MIDI_GM_PATCH_DEF(/* 106 */ "Banjo")
MIDI_GM_PATCH_DEF(/* 107 */ "Shamisen")
MIDI_GM_PATCH_DEF(/* 108 */ "Koto")
MIDI_GM_PATCH_DEF(/* 109 */ "Kalimba")
MIDI_GM_PATCH_DEF(/* 110 */ "Bag pipe")
MIDI_GM_PATCH_DEF(/* 111 */ "Fiddle")
MIDI_GM_PATCH_DEF(/* 112 */ "Shanai")
MIDI_GM_PATCH_DEF(/* 113 */ "Tinkle Bell")
MIDI_GM_PATCH_DEF(/* 114 */ "Agogo")
MIDI_GM_PATCH_DEF(/* 115 */ "Steel Drums")
MIDI_GM_PATCH_DEF(/* 116 */ "Woodblock")
MIDI_GM_PATCH_DEF(/* 117 */ "Taiko Drum")
MIDI_GM_PATCH_DEF(/* 118 */ "Melodic Tom")
MIDI_GM_PATCH_DEF(/* 119 */ "Synth Drum")
MIDI_GM_PATCH_DEF(/* 120 */ "Reverse Cymbal")
MIDI_GM_PATCH_DEF(/* 121 */ "Guitar Fret Noise")
MIDI_GM_PATCH_DEF(/* 122 */ "Breath Noise")
MIDI_GM_PATCH_DEF(/* 123 */ "Seashore")
MIDI_GM_PATCH_DEF(/* 124 */ "Bird Tweet")
MIDI_GM_PATCH_DEF(/* 125 */ "Telephone Ring")
MIDI_GM_PATCH_DEF(/* 126 */ "Helicopter")
MIDI_GM_PATCH_DEF(/* 127 */ "Applause")
MIDI_GM_PATCH_DEF(/* 128 */ "Gunshot")

#endif	// MIDI_GM_PATCH_DEF
#undef MIDI_GM_PATCH_DEF

#ifdef MIDI_GM_DRUM_DEF

// GS extensions are included

#define MIDI_GM_DRUM_FIRST 27
#define MIDI_GM_DRUM_LAST 87

MIDI_GM_DRUM_DEF(/* 27*/ "High Q")
MIDI_GM_DRUM_DEF(/* 28*/ "Slap")
MIDI_GM_DRUM_DEF(/* 29*/ "Scratch Push")
MIDI_GM_DRUM_DEF(/* 30*/ "Scratch Pull")
MIDI_GM_DRUM_DEF(/* 31*/ "Sticks")
MIDI_GM_DRUM_DEF(/* 32*/ "Square Click")
MIDI_GM_DRUM_DEF(/* 33*/ "Metronome Click")
MIDI_GM_DRUM_DEF(/* 34*/ "Metronome Bell")
MIDI_GM_DRUM_DEF(/* 35*/ "Acoustic Bass Drum")
MIDI_GM_DRUM_DEF(/* 36*/ "Bass Drum 1")
MIDI_GM_DRUM_DEF(/* 37*/ "Side Stick")
MIDI_GM_DRUM_DEF(/* 38*/ "Acoustic Snare")
MIDI_GM_DRUM_DEF(/* 39*/ "Hand Clap")
MIDI_GM_DRUM_DEF(/* 40*/ "Electric Snare")
MIDI_GM_DRUM_DEF(/* 41*/ "Low Floor Tom")
MIDI_GM_DRUM_DEF(/* 42*/ "Closed Hi Hat")
MIDI_GM_DRUM_DEF(/* 43*/ "High Floor Tom")
MIDI_GM_DRUM_DEF(/* 44*/ "Pedal Hi-Hat")
MIDI_GM_DRUM_DEF(/* 45*/ "Low Tom")
MIDI_GM_DRUM_DEF(/* 46*/ "Open Hi-Hat")
MIDI_GM_DRUM_DEF(/* 47*/ "Low-Mid Tom")
MIDI_GM_DRUM_DEF(/* 48*/ "Hi-Mid Tom")
MIDI_GM_DRUM_DEF(/* 49*/ "Crash Cymbal 1")
MIDI_GM_DRUM_DEF(/* 50*/ "High Tom")
MIDI_GM_DRUM_DEF(/* 51*/ "Ride Cymbal 1")
MIDI_GM_DRUM_DEF(/* 52*/ "Chinese Cymbal")
MIDI_GM_DRUM_DEF(/* 53*/ "Ride Bell")
MIDI_GM_DRUM_DEF(/* 54*/ "Tambourine")
MIDI_GM_DRUM_DEF(/* 55*/ "Splash Cymbal")
MIDI_GM_DRUM_DEF(/* 56*/ "Cowbell")
MIDI_GM_DRUM_DEF(/* 57*/ "Crash Cymbal 2")
MIDI_GM_DRUM_DEF(/* 58*/ "Vibraslap")
MIDI_GM_DRUM_DEF(/* 59*/ "Ride Cymbal 2")
MIDI_GM_DRUM_DEF(/* 60*/ "Hi Bongo")
MIDI_GM_DRUM_DEF(/* 61*/ "Low Bongo")
MIDI_GM_DRUM_DEF(/* 62*/ "Mute Hi Conga")
MIDI_GM_DRUM_DEF(/* 63*/ "Open Hi Conga")
MIDI_GM_DRUM_DEF(/* 64*/ "Low Conga")
MIDI_GM_DRUM_DEF(/* 65*/ "High Timbale")
MIDI_GM_DRUM_DEF(/* 66*/ "Low Timbale")
MIDI_GM_DRUM_DEF(/* 67*/ "High Agogo")
MIDI_GM_DRUM_DEF(/* 68*/ "Low Agogo")
MIDI_GM_DRUM_DEF(/* 69*/ "Cabasa")
MIDI_GM_DRUM_DEF(/* 70*/ "Maracas")
MIDI_GM_DRUM_DEF(/* 71*/ "Short Whistle")
MIDI_GM_DRUM_DEF(/* 72*/ "Long Whistle")
MIDI_GM_DRUM_DEF(/* 73*/ "Short Guiro")
MIDI_GM_DRUM_DEF(/* 74*/ "Long Guiro")
MIDI_GM_DRUM_DEF(/* 75*/ "Claves")
MIDI_GM_DRUM_DEF(/* 76*/ "Hi Wood Block")
MIDI_GM_DRUM_DEF(/* 77*/ "Low Wood Block")
MIDI_GM_DRUM_DEF(/* 78*/ "Mute Cuica")
MIDI_GM_DRUM_DEF(/* 79*/ "Open Cuica")
MIDI_GM_DRUM_DEF(/* 80*/ "Mute Triangle")
MIDI_GM_DRUM_DEF(/* 81*/ "Open Triangle")
MIDI_GM_DRUM_DEF(/* 82*/ "Shaker")
MIDI_GM_DRUM_DEF(/* 83*/ "Jingle Bell")
MIDI_GM_DRUM_DEF(/* 84*/ "Belltree")
MIDI_GM_DRUM_DEF(/* 85*/ "Castanets")
MIDI_GM_DRUM_DEF(/* 86*/ "Mute Surdo")
MIDI_GM_DRUM_DEF(/* 87*/ "Open Surdo ")

#endif	// MIDI_GM_DRUM_DEF
#undef MIDI_GM_DRUM_DEF
