//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Whorld.rc
//
#define IDR_MAINFRAME                   101
#define IDR_LIST_COL_HDR                102
#define IDR_MAINFRAME_256               103
#define IDR_MAPPING_CTX                 104
#define IDR_PLAYLIST                    105
#define IDR_POPUP_EDIT                  106
#define IDR_THEME_MENU                  107
#define IDR_WhorldTYPE                  108
#define IDD_ABOUTBOX                    109
#define IDD_EXPORT                      110
#define IDD_GLOBAL_ROW                  111
#define IDD_MASTER_ROW                  112
#define IDD_MOVIE_EXPORT                113
#define IDD_OPTIONS                     114
#define IDD_PARAM_ROW                   115
#define IDD_PROGRESS                    116
#define IDD_ROW_FORM                    117
#define IDS_APP_ERR_BAD_EXPORT_IMAGE_FOLDER 200
#define IDS_APP_ERR_CANT_CREATE_APP_DATA_FOLDER 201
#define IDS_APP_ERR_CANT_CREATE_PROGRESS_DLG 202
#define IDS_APP_ERR_CANT_CREATE_RENDER_THREAD 203
#define IDS_APP_ERR_CANT_CREATE_RENDER_WINDOW 204
#define IDS_APP_ERR_CANT_DETACH_RENDER_WINDOW 205
#define IDS_APP_ERR_CANT_GET_DISPLAY_SETTINGS 206
#define IDS_APP_ERR_CANT_GET_MONITOR_INFO 207
#define IDS_APP_ERR_CANT_REMOVE_KEYBOARD_HOOK 208
#define IDS_APP_ERR_CANT_SET_KEYBOARD_HOOK 209
#define IDS_APP_ERR_RENDERING_TOO_SLOW  210
#define IDS_APP_ERR_RENDER_QUEUE_FULL   211
#define IDS_APP_LICENSE                 212
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    213
#define IDS_BAR_Globals                 214
#define IDS_BAR_Mapping                 215
#define IDS_BAR_Master                  216
#define IDS_BAR_Movie                   217
#define IDS_BAR_Params                  218
#define IDS_CHAN_STAT_CHAN_AFT          219
#define IDS_CHAN_STAT_CONTROL           220
#define IDS_CHAN_STAT_INTERNAL          221
#define IDS_CHAN_STAT_KEY_AFT           222
#define IDS_CHAN_STAT_MODULATOR         223
#define IDS_CHAN_STAT_NOTE              224
#define IDS_CHAN_STAT_NOTE_OFF          225
#define IDS_CHAN_STAT_NOTE_ON           226
#define IDS_CHAN_STAT_PATCH             227
#define IDS_CHAN_STAT_TEMPO             228
#define IDS_CHAN_STAT_WHEEL             229
#define IDS_DOC_BAD_FORMAT              230
#define IDS_DOC_NEWER_VERSION           231
#define IDS_EDIT_CUT                    232
#define IDS_EDIT_DELETE                 233
#define IDS_EDIT_INSERT                 234
#define IDS_EDIT_LEARN                  235
#define IDS_EDIT_LEARN_MULTI            236
#define IDS_EDIT_MENU                   237
#define IDS_EDIT_MOVE                   238
#define IDS_EDIT_PASTE                  239
#define IDS_EDIT_REDO_PREFIX            240
#define IDS_EDIT_SORT                   241
#define IDS_EDIT_UNDO_PREFIX            242
#define IDS_EXPORT_ALL_SNAPSHOTS        243
#define IDS_EXPORT_MOVIE                244
#define IDS_FILE_EXPORT_SAVE_AS         245
#define IDS_GRID_ERR_BAD_TIME_FORMAT    246
#define IDS_MAIN_Convex                 247
#define IDS_MAIN_DrawMode               248
#define IDS_MAIN_Hue                    249
#define IDS_MAIN_InvertColor            250
#define IDS_MAIN_LoopHue                251
#define IDS_MAIN_Mirror                 252
#define IDS_MAIN_OrgMotion              253
#define IDS_MAIN_Origin                 254
#define IDS_MAIN_Reverse                255
#define IDS_MAIN_ZoomCenter             256
#define IDS_MAPPING_COL_CHANNEL         257
#define IDS_MAPPING_COL_CONTROL         258
#define IDS_MAPPING_COL_END             259
#define IDS_MAPPING_COL_EVENT           260
#define IDS_MAPPING_COL_NUMBER          261
#define IDS_MAPPING_COL_PROPERTY        262
#define IDS_MAPPING_COL_START           263
#define IDS_MAPPING_COL_TARGET          264
#define IDS_MAP_TARGET_Clear            265
#define IDS_MAP_TARGET_Convex           266
#define IDS_MAP_TARGET_Fill             267
#define IDS_MAP_TARGET_LoopHue          268
#define IDS_MAP_TARGET_Mirror           269
#define IDS_MAP_TARGET_OriginDrag       270
#define IDS_MAP_TARGET_OriginRandom     271
#define IDS_MAP_TARGET_OriginX          272
#define IDS_MAP_TARGET_OriginY          273
#define IDS_MAP_TARGET_Outline          274
#define IDS_MAP_TARGET_Pause            275
#define IDS_MAP_TARGET_RandomOrigin     276
#define IDS_MAP_TARGET_RandomPhase      277
#define IDS_MAP_TARGET_Reverse          278
#define IDS_MAP_TARGET_ZoomCenter       279
#define IDS_MASTER_CanvasScale          280
#define IDS_MASTER_Copies               281
#define IDS_MASTER_Damping              282
#define IDS_MASTER_HueSpan              283
#define IDS_MASTER_Rings                284
#define IDS_MASTER_Speed                285
#define IDS_MASTER_Spread               286
#define IDS_MASTER_Tempo                287
#define IDS_MASTER_Trail                288
#define IDS_MASTER_Zoom                 289
#define IDS_MEX_BAD_RANGE               290
#define IDS_MEX_BAD_TIME                291
#define IDS_MIDI_DEVICES_MISSING        292
#define IDS_MIDI_INPUT                  293
#define IDS_MIDI_OUTPUT                 294
#define IDS_MIDI_SYS_STAT_ACTIVE_SENSING 295
#define IDS_MIDI_SYS_STAT_CLOCK         296
#define IDS_MIDI_SYS_STAT_CONTINUE      297
#define IDS_MIDI_SYS_STAT_EOX           298
#define IDS_MIDI_SYS_STAT_MTC_QTR_FRAME 299
#define IDS_MIDI_SYS_STAT_SONG_POSITION 300
#define IDS_MIDI_SYS_STAT_SONG_SELECT   301
#define IDS_MIDI_SYS_STAT_START         302
#define IDS_MIDI_SYS_STAT_STOP          303
#define IDS_MIDI_SYS_STAT_SYSEX         304
#define IDS_MIDI_SYS_STAT_SYSTEM_RESET  305
#define IDS_MIDI_SYS_STAT_TUNE_REQUEST  306
#define IDS_MOVIE_EXPORT_OVERWRITE_WARN 307
#define IDS_MOVIE_OPEN                  308
#define IDS_MOVIE_SAVE_AS               309
#define IDS_NONE                        310
#define IDS_NOT_APPLICABLE              311
#define IDS_OPT_DESC_Export_bPromptUser 312
#define IDS_OPT_DESC_Export_bUseViewSize 313
#define IDS_OPT_DESC_Export_nImageHeight 314
#define IDS_OPT_DESC_Export_nImageWidth 315
#define IDS_OPT_DESC_Export_nScaleToFit 316
#define IDS_OPT_DESC_Export_sImageFolder 317
#define IDS_OPT_DESC_General_nMRUItems  318
#define IDS_OPT_DESC_Input_fWheelSense  319
#define IDS_OPT_DESC_Midi_iInputDevice  320
#define IDS_OPT_DESC_Snapshot_bLetterbox 321
#define IDS_OPT_DESC_Snapshot_iLegacySize 322
#define IDS_OPT_GROUP_Export            323
#define IDS_OPT_GROUP_General           324
#define IDS_OPT_GROUP_Input             325
#define IDS_OPT_GROUP_Midi              326
#define IDS_OPT_GROUP_Snapshot          327
#define IDS_OPT_LEGACY_SIZE_SVGA        328
#define IDS_OPT_LEGACY_SIZE_VGA         329
#define IDS_OPT_LEGACY_SIZE_XGA         330
#define IDS_OPT_NAME_Export_bPromptUser 331
#define IDS_OPT_NAME_Export_bUseViewSize 332
#define IDS_OPT_NAME_Export_nImageHeight 333
#define IDS_OPT_NAME_Export_nImageWidth 334
#define IDS_OPT_NAME_Export_nScaleToFit 335
#define IDS_OPT_NAME_Export_sImageFolder 336
#define IDS_OPT_NAME_General_nMRUItems  337
#define IDS_OPT_NAME_Input_fWheelSense  338
#define IDS_OPT_NAME_Midi_iInputDevice  339
#define IDS_OPT_NAME_Snapshot_bLetterbox 340
#define IDS_OPT_NAME_Snapshot_iLegacySize 341
#define IDS_OPT_SCALE_TO_FIT_Both       342
#define IDS_OPT_SCALE_TO_FIT_Height     343
#define IDS_OPT_SCALE_TO_FIT_None       344
#define IDS_OPT_SCALE_TO_FIT_Width      345
#define IDS_PARAM_AspectRatio           346
#define IDS_PARAM_BkHue                 347
#define IDS_PARAM_BkLightness           348
#define IDS_PARAM_BkSaturation          349
#define IDS_PARAM_ColorSpeed            350
#define IDS_PARAM_EvenCurve             351
#define IDS_PARAM_EvenShear             352
#define IDS_PARAM_Lightness             353
#define IDS_PARAM_LineWidth             354
#define IDS_PARAM_OddCurve              355
#define IDS_PARAM_OddShear              356
#define IDS_PARAM_Pinwheel              357
#define IDS_PARAM_PolySides             358
#define IDS_PARAM_RingGrowth            359
#define IDS_PARAM_RingSpacing           360
#define IDS_PARAM_RotateSpeed           361
#define IDS_PARAM_Saturation            362
#define IDS_PARAM_SkewAngle             363
#define IDS_PARAM_SkewRadius            364
#define IDS_PARAM_StarFactor            365
#define IDS_PROPS_MORE_COLORS           366
#define IDS_PROW_Amp                    367
#define IDS_PROW_Freq                   368
#define IDS_PROW_Global                 369
#define IDS_PROW_NAME_STATIC            370
#define IDS_PROW_PW                     371
#define IDS_PROW_VAL_SLIDER             372
#define IDS_PROW_Val                    373
#define IDS_PROW_Wave                   374
#define IDS_RESET_ALL_OPTIONS           375
#define IDS_SEQ_MIDI_ERROR              376
#define IDS_SNAPSHOT_SAVE_AS            377
#define IDS_TOOLBAR_CUSTOMIZE           378
#define IDS_TOOLBAR_STANDARD            379
#define IDS_WAVE_PULSE                  380
#define IDS_WAVE_RAMP_DOWN              381
#define IDS_WAVE_RAMP_UP                382
#define IDS_WAVE_RANDOM                 383
#define IDS_WAVE_RANDOM_RAMP            384
#define IDS_WAVE_SINE                   385
#define IDS_WAVE_SQUARE                 386
#define IDS_WAVE_TRIANGLE               387
#define IDS_WINDOW_RESET_LAYOUT_WARN    388
#define IDP_OLE_INIT_FAILED             389
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_CURSOR_DRAG_MULTI           1003
#define IDC_CURSOR_DRAG_SINGLE          1004
#define IDC_EXPORT_HEIGHT_EDIT          1005
#define IDC_EXPORT_SCALE_TO_FIT_COMBO   1006
#define IDC_EXPORT_USE_VIEW_SIZE_CHECK  1007
#define IDC_EXPORT_WIDTH_EDIT           1008
#define IDC_MAST_NAME_STATIC            1009
#define IDC_MAST_VAL_EDIT               1010
#define IDC_MAST_VAL_SLIDER             1011
#define IDC_MEX_DURATION_EDIT           1012
#define IDC_MEX_FRAME_HEIGHT_EDIT       1013
#define IDC_MEX_FRAME_RATE_EDIT         1014
#define IDC_MEX_FRAME_SEL_TYPE_1        1015
#define IDC_MEX_FRAME_SEL_TYPE_2        1016
#define IDC_MEX_FRAME_SIZE_COMBO        1017
#define IDC_MEX_FRAME_WIDTH_EDIT        1018
#define IDC_MEX_RANGE_END_EDIT          1019
#define IDC_MEX_RANGE_START_EDIT        1020
#define IDC_MEX_SCALE_TO_FIT_COMBO      1021
#define IDC_MEX_TIME_UNIT_1             1022
#define IDC_MEX_TIME_UNIT_2             1023
#define IDC_OPTIONS_GRID                1024
#define IDC_OPTIONS_RESET_ALL           1025
#define IDC_PROGRESS                    1026
#define IDC_PROGRESS_PERCENT            1027
#define IDC_PROW_AMP_SPIN               1028
#define IDC_PROW_Amp                    1029
#define IDC_PROW_FREQ_SPIN              1030
#define IDC_PROW_Freq                   1031
#define IDC_PROW_NAME_STATIC            1032
#define IDC_PROW_PW                     1033
#define IDC_PROW_PW_SPIN                1034
#define IDC_PROW_VAL_SLIDER             1035
#define IDC_PROW_VAL_SPIN               1036
#define IDC_PROW_Val                    1037
#define IDC_PROW_Wave                   1038
#define ID_APP_HOME_PAGE                32771
#define ID_EDIT_DELETE                  32772
#define ID_EDIT_INSERT                  32773
#define ID_FILE_EXPORT                  32774
#define ID_FILE_LOAD_SNAPSHOT           32775
#define ID_FILE_TAKE_SNAPSHOT           32776
#define ID_IMAGE_CONVEX                 32777
#define ID_IMAGE_FILL                   32778
#define ID_IMAGE_LOOP_HUE               32779
#define ID_IMAGE_MIRROR                 32780
#define ID_IMAGE_ORIGIN_CENTER          32781
#define ID_IMAGE_ORIGIN_DRAG            32782
#define ID_IMAGE_ORIGIN_RANDOM          32783
#define ID_IMAGE_OUTLINE                32784
#define ID_IMAGE_RANDOM_PHASE           32785
#define ID_IMAGE_REVERSE                32786
#define ID_IMAGE_ZOOM_CENTER            32787
#define ID_LIST_COL_HDR_RESET           32788
#define ID_MOVIE_EXPORT                 32789
#define ID_MOVIE_PLAY                   32790
#define ID_MOVIE_RECORD                 32791
#define ID_MOVIE_REWIND                 32792
#define ID_PLAYLIST_MRU_FILE1           32793
#define ID_PLAYLIST_MRU_FILE10          32794
#define ID_PLAYLIST_MRU_FILE11          32795
#define ID_PLAYLIST_MRU_FILE12          32796
#define ID_PLAYLIST_MRU_FILE13          32797
#define ID_PLAYLIST_MRU_FILE14          32798
#define ID_PLAYLIST_MRU_FILE15          32799
#define ID_PLAYLIST_MRU_FILE16          32800
#define ID_PLAYLIST_MRU_FILE2           32801
#define ID_PLAYLIST_MRU_FILE3           32802
#define ID_PLAYLIST_MRU_FILE4           32803
#define ID_PLAYLIST_MRU_FILE5           32804
#define ID_PLAYLIST_MRU_FILE6           32805
#define ID_PLAYLIST_MRU_FILE7           32806
#define ID_PLAYLIST_MRU_FILE8           32807
#define ID_PLAYLIST_MRU_FILE9           32808
#define ID_PLAYLIST_NEW                 32809
#define ID_PLAYLIST_OPEN                32810
#define ID_PLAYLIST_SAVE                32811
#define ID_PLAYLIST_SAVE_AS             32812
#define ID_SNAPSHOT_EXPORT_ALL          32813
#define ID_SNAPSHOT_FIRST               32814
#define ID_SNAPSHOT_INFO                32815
#define ID_SNAPSHOT_LAST                32816
#define ID_SNAPSHOT_NEXT                32817
#define ID_SNAPSHOT_PREV                32818
#define ID_STATUS_PANE_FRAME_RATE       32819
#define ID_STATUS_PANE_RECORD_TIME      32820
#define ID_STATUS_PANE_RING_COUNT       32821
#define ID_VIEW_APPLOOK_OFF_2003        32822
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32823
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32824
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32825
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32826
#define ID_VIEW_APPLOOK_OFF_XP          32827
#define ID_VIEW_APPLOOK_VS_2005         32828
#define ID_VIEW_APPLOOK_VS_2008         32829
#define ID_VIEW_APPLOOK_WINDOWS_7       32830
#define ID_VIEW_APPLOOK_WIN_2000        32831
#define ID_VIEW_APPLOOK_WIN_XP          32832
#define ID_VIEW_BAR_Globals             32833
#define ID_VIEW_BAR_Mapping             32834
#define ID_VIEW_BAR_Master              32835
#define ID_VIEW_BAR_Movie               32836
#define ID_VIEW_BAR_Params              32837
#define ID_VIEW_CUSTOMIZE               32838
#define ID_VIEW_MIDI_LEARN              32839
#define ID_VIEW_OPTIONS                 32840
#define ID_WINDOW_CLEAR                 32841
#define ID_WINDOW_DETACH                32842
#define ID_WINDOW_FULLSCREEN            32843
#define ID_WINDOW_PAUSE                 32844
#define ID_WINDOW_RESET_LAYOUT          32845
#define ID_WINDOW_STEP                  32846

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        390
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
