//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Whorld.rc
//
#define IDR_MAINFRAME                   101
#define IDR_MAINFRAME_256               102
#define IDR_POPUP_EDIT                  103
#define IDR_THEME_MENU                  104
#define IDR_WhorldTYPE                  105
#define IDD_ABOUTBOX                    106
#define IDD_EXPORT                      107
#define IDD_MASTER_ROW                  108
#define IDD_OPTIONS                     109
#define IDD_PARAM_ROW                   110
#define IDD_PROGRESS                    111
#define IDD_ROW_FORM                    112
#define IDS_APP_ERR_BAD_EXPORT_IMAGE_FOLDER 200
#define IDS_APP_ERR_CANT_CREATE_RENDER_THREAD 201
#define IDS_APP_ERR_CANT_CREATE_RENDER_WINDOW 202
#define IDS_APP_ERR_CANT_DETACH_RENDER_WINDOW 203
#define IDS_APP_ERR_CANT_GET_DISPLAY_SETTINGS 204
#define IDS_APP_ERR_CANT_GET_MONITOR_INFO 205
#define IDS_APP_ERR_CANT_REMOVE_KEYBOARD_HOOK 206
#define IDS_APP_ERR_CANT_SET_KEYBOARD_HOOK 207
#define IDS_APP_ERR_TOO_MANY_RENDER_COMMANDS 208
#define IDS_APP_LICENSE                 209
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    210
#define IDS_BAR_Master                  211
#define IDS_BAR_Params                  212
#define IDS_DOC_BAD_FORMAT              213
#define IDS_EDIT_MENU                   214
#define IDS_EDIT_REDO_PREFIX            215
#define IDS_EDIT_UNDO_PREFIX            216
#define IDS_GRID_ERR_BAD_TIME_FORMAT    217
#define IDS_MAIN_Convex                 218
#define IDS_MAIN_DrawMode               219
#define IDS_MAIN_Hue                    220
#define IDS_MAIN_InvertColor            221
#define IDS_MAIN_LoopHue                222
#define IDS_MAIN_Mirror                 223
#define IDS_MAIN_OrgMotion              224
#define IDS_MAIN_Origin                 225
#define IDS_MAIN_Reverse                226
#define IDS_MAIN_ZoomCenter             227
#define IDS_MASTER_CanvasScale          228
#define IDS_MASTER_Copies               229
#define IDS_MASTER_Damping              230
#define IDS_MASTER_HueLoopLength        231
#define IDS_MASTER_Rings                232
#define IDS_MASTER_Speed                233
#define IDS_MASTER_Spread               234
#define IDS_MASTER_Tempo                235
#define IDS_MASTER_Trail                236
#define IDS_MASTER_Zoom                 237
#define IDS_OPT_DESC_Export_bPromptUser 238
#define IDS_OPT_DESC_Export_bScaleToFit 239
#define IDS_OPT_DESC_Export_bUseViewSize 240
#define IDS_OPT_DESC_Export_nImageHeight 241
#define IDS_OPT_DESC_Export_nImageWidth 242
#define IDS_OPT_DESC_Export_sImageFolder 243
#define IDS_OPT_GROUP_Export            244
#define IDS_OPT_NAME_Export_bPromptUser 245
#define IDS_OPT_NAME_Export_bScaleToFit 246
#define IDS_OPT_NAME_Export_bUseViewSize 247
#define IDS_OPT_NAME_Export_nImageHeight 248
#define IDS_OPT_NAME_Export_nImageWidth 249
#define IDS_OPT_NAME_Export_sImageFolder 250
#define IDS_PARAM_AspectRatio           251
#define IDS_PARAM_BkHue                 252
#define IDS_PARAM_BkLightness           253
#define IDS_PARAM_BkSaturation          254
#define IDS_PARAM_ColorSpeed            255
#define IDS_PARAM_EvenCurve             256
#define IDS_PARAM_EvenShear             257
#define IDS_PARAM_Lightness             258
#define IDS_PARAM_LineWidth             259
#define IDS_PARAM_OddCurve              260
#define IDS_PARAM_OddShear              261
#define IDS_PARAM_Pinwheel              262
#define IDS_PARAM_PolySides             263
#define IDS_PARAM_RingGrowth            264
#define IDS_PARAM_RingSpacing           265
#define IDS_PARAM_RotateSpeed           266
#define IDS_PARAM_Saturation            267
#define IDS_PARAM_SkewAngle             268
#define IDS_PARAM_SkewRadius            269
#define IDS_PARAM_StarFactor            270
#define IDS_PROPS_MORE_COLORS           271
#define IDS_PROW_Amp                    272
#define IDS_PROW_Freq                   273
#define IDS_PROW_NAME_STATIC            274
#define IDS_PROW_PW                     275
#define IDS_PROW_VAL_SLIDER             276
#define IDS_PROW_Val                    277
#define IDS_PROW_Wave                   278
#define IDS_RESET_ALL_OPTIONS           279
#define IDS_TOOLBAR_CUSTOMIZE           280
#define IDS_TOOLBAR_STANDARD            281
#define IDS_WAVE_PULSE                  282
#define IDS_WAVE_RAMP_DOWN              283
#define IDS_WAVE_RAMP_UP                284
#define IDS_WAVE_RANDOM                 285
#define IDS_WAVE_RANDOM_RAMP            286
#define IDS_WAVE_SINE                   287
#define IDS_WAVE_SQUARE                 288
#define IDS_WAVE_TRIANGLE               289
#define IDS_WINDOW_RESET_LAYOUT_WARN    290
#define IDP_OLE_INIT_FAILED             291
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_EXPORT_HEIGHT               1003
#define IDC_EXPORT_RESIZING1            1004
#define IDC_EXPORT_RESIZING2            1005
#define IDC_EXPORT_USE_VIEW_SIZE        1006
#define IDC_EXPORT_WIDTH                1007
#define IDC_MAST_NAME_STATIC            1008
#define IDC_MAST_VAL_EDIT               1009
#define IDC_MAST_VAL_SLIDER             1010
#define IDC_OPTIONS_GRID                1011
#define IDC_OPTIONS_RESET_ALL           1012
#define IDC_PROGRESS                    1013
#define IDC_PROGRESS_PERCENT            1014
#define IDC_PROW_AMP_SPIN               1015
#define IDC_PROW_Amp                    1016
#define IDC_PROW_FREQ_SPIN              1017
#define IDC_PROW_Freq                   1018
#define IDC_PROW_NAME_STATIC            1019
#define IDC_PROW_PW                     1020
#define IDC_PROW_PW_SPIN                1021
#define IDC_PROW_VAL_SLIDER             1022
#define IDC_PROW_VAL_SPIN               1023
#define IDC_PROW_Val                    1024
#define IDC_PROW_Wave                   1025
#define ID_APP_HOME_PAGE                32771
#define ID_EDIT_DELETE                  32772
#define ID_EDIT_INSERT                  32773
#define ID_FILE_EXPORT                  32774
#define ID_IMAGE_CONVEX                 32775
#define ID_IMAGE_FILL                   32776
#define ID_IMAGE_MIRROR                 32777
#define ID_IMAGE_ORIGIN_CENTER          32778
#define ID_IMAGE_ORIGIN_DRAG            32779
#define ID_IMAGE_ORIGIN_RANDOM          32780
#define ID_IMAGE_OUTLINE                32781
#define ID_IMAGE_RANDOM_PHASE           32782
#define ID_IMAGE_REVERSE                32783
#define ID_STATUS_PANE_FRAME_RATE       32784
#define ID_STATUS_PANE_RING_COUNT       32785
#define ID_VIEW_APPLOOK_OFF_2003        32786
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32787
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32788
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32789
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32790
#define ID_VIEW_APPLOOK_OFF_XP          32791
#define ID_VIEW_APPLOOK_VS_2005         32792
#define ID_VIEW_APPLOOK_VS_2008         32793
#define ID_VIEW_APPLOOK_WINDOWS_7       32794
#define ID_VIEW_APPLOOK_WIN_2000        32795
#define ID_VIEW_APPLOOK_WIN_XP          32796
#define ID_VIEW_BAR_Master              32797
#define ID_VIEW_BAR_Params              32798
#define ID_VIEW_CUSTOMIZE               32799
#define ID_VIEW_OPTIONS                 32800
#define ID_WINDOW_CLEAR                 32801
#define ID_WINDOW_DETACH                32802
#define ID_WINDOW_FULLSCREEN            32803
#define ID_WINDOW_PAUSE                 32804
#define ID_WINDOW_RESET_LAYOUT          32805
#define ID_WINDOW_STEP                  32806

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        292
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
